// The entries the approved designs actually draw (desktop BOX 48/49/50, mobile BOX 75/76/77).
// Reproduced row for row so a screen can be held against its design tile, plus the Admin spec
// §10.4 example quoted verbatim — `aud_01J8XKQ2M4` is that example, timestamp included.
//
// The rest of the ledger is generated in `audit.fixtures.ts`; only these carry design meaning.

import { AUDIT_ACTIONS } from "./audit.types";
import {
  AUDIT_ADMIN_KEYS,
  bookingTarget as booking,
  providerTarget as provider,
  type AuditSeed,
} from "./auditSeed";

export const AUDIT_DESIGN_SEEDS: readonly AuditSeed[] = [
  {
    id: "aud_c07b5512",
    at: "2026-07-20 17:20",
    admin: AUDIT_ADMIN_KEYS.ravi,
    action: AUDIT_ACTIONS.paymentRefundReverse,
    target: booking("8790"),
    before: { refunded: "₹1,499" },
    after: { refunded: "₹0" },
    reasonCode: "REFUND_ISSUED_IN_ERROR",
    note: "Refund was raised against the wrong booking. Reversed with the customer's agreement.",
    evidence: [0, 1, 1],
    compensatesEntryId: "aud_4c81de20",
  },
  {
    id: "aud_7d1e9044",
    at: "2026-07-20 17:47",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.paymentRefund,
    target: booking("8804"),
    before: { refunded: "₹0" },
    after: { refunded: "₹899" },
    reasonCode: "PROVIDER_NO_SHOW",
  },
  {
    // Admin spec §10.4, verbatim: id, timestamp, admin, action, risk, target, reason and evidence.
    id: "aud_01J8XKQ2M4",
    at: "2026-07-20 15:42",
    timestamp: "2026-07-20T10:12:11.482Z",
    admin: AUDIT_ADMIN_KEYS.ravi,
    action: AUDIT_ACTIONS.bookingManualComplete,
    target: { type: "booking", id: "bkg_8823", reference: "#B-8823" },
    before: { state: "Waiting Completion OTP" },
    after: { state: "Completed (Admin Verified)" },
    reasonCode: "CUSTOMER_UNREACHABLE",
    note: "Customer left for work before the technician finished. Photos confirm the unit was serviced and reassembled. Called twice, no answer.",
    // Two photos and one call log — the counts the spec's own example carries.
    evidence: [2, 1, 0],
  },
  {
    id: "aud_5b3a71c9",
    at: "2026-07-20 15:48",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.bookingCancel,
    target: booking("8811"),
    before: { state: "Escalated" },
    after: { state: "Cancelled" },
    reasonCode: "SAFETY_CONCERN",
    evidence: [0, 2, 1],
  },
  {
    id: "aud_2e8f40d1",
    at: "2026-07-20 15:41",
    admin: AUDIT_ADMIN_KEYS.ravi,
    action: AUDIT_ACTIONS.bookingAssign,
    target: booking("8817"),
    before: { provider: "unassigned" },
    after: { provider: "Suresh Mehta (PRV-882)" },
    reasonCode: "ESCALATION_RESCUE",
  },
  {
    id: "aud_8a44c130",
    at: "2026-07-20 14:15",
    admin: AUDIT_ADMIN_KEYS.ravi,
    action: AUDIT_ACTIONS.providerSuspend,
    target: provider("914"),
    before: { status: "Active" },
    after: { status: "Suspended 7 days" },
    reasonCode: "CUSTOMER_SAFETY_COMPLAINT",
    evidence: [1, 1, 1],
  },
  {
    id: "aud_4c81de20",
    at: "2026-07-20 13:02",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.paymentRefund,
    target: booking("8790"),
    before: { refunded: "₹0" },
    after: { refunded: "₹1,499" },
    reasonCode: "POOR_SERVICE_QUALITY",
    note: "Unit was still not cooling an hour after the technician left. Customer sent a video.",
    evidence: [2, 1, 1],
  },
  {
    id: "aud_6f90ab27",
    at: "2026-07-20 12:40",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.paymentRefund,
    target: booking("8776"),
    before: { refunded: "₹0" },
    after: { refunded: "₹499" },
    reasonCode: "CANCELLED_AFTER_ARRIVAL",
  },
  {
    id: "aud_1c55e8b3",
    at: "2026-07-20 11:38",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.paymentRefund,
    target: booking("8786"),
    before: { refunded: "₹0" },
    after: { refunded: "₹2,199" },
    reasonCode: "DUPLICATE_CHARGE",
  },
  {
    id: "aud_9d02f7ae",
    at: "2026-07-20 11:05",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.paymentRefund,
    target: booking("8768"),
    before: { refunded: "₹0" },
    after: { refunded: "₹1,299" },
    reasonCode: "PROVIDER_NO_SHOW",
  },
  {
    id: "aud_3ba6c015",
    at: "2026-07-20 10:14",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.paymentRefund,
    target: booking("8771"),
    before: { refunded: "₹0" },
    after: { refunded: "₹450" },
    reasonCode: "PARTIAL_SERVICE",
  },
  {
    id: "aud_0e7714dc",
    at: "2026-07-20 09:52",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.paymentRefund,
    target: booking("8755"),
    before: { refunded: "₹0" },
    after: { refunded: "₹749" },
    reasonCode: "PARTIAL_SERVICE",
  },
  {
    id: "aud_c1d38f62",
    at: "2026-07-19 18:40",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.bookingAssign,
    target: booking("8764"),
    before: { provider: "unassigned" },
    after: { provider: "Kiran Reddy (PRV-771)" },
    reasonCode: "ESCALATION_RESCUE",
  },
  {
    id: "aud_a90b2e58",
    at: "2026-07-19 17:12",
    admin: AUDIT_ADMIN_KEYS.ravi,
    action: AUDIT_ACTIONS.bookingManualComplete,
    target: booking("8752"),
    before: { state: "Waiting Completion OTP" },
    after: { state: "Completed (Admin Verified)" },
    reasonCode: "OTP_NOT_RECEIVED",
    evidence: [4, 1, 1],
  },
  {
    id: "aud_74fe10c9",
    at: "2026-07-19 11:28",
    admin: AUDIT_ADMIN_KEYS.priya,
    action: AUDIT_ACTIONS.paymentRefund,
    target: booking("8741"),
    before: { refunded: "₹0" },
    after: { refunded: "₹899" },
    reasonCode: "DUPLICATE_CHARGE",
  },
];
