// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/kokkondaBhanuteja/sethu-care/internal/money"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (name, slug, sort_order)
VALUES ($1, $2, $3)
RETURNING id, name, slug, sort_order, is_active
`

type CreateCategoryParams struct {
	Name      string
	Slug      string
	SortOrder int32
}

type CreateCategoryRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	SortOrder int32
	IsActive  bool
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (CreateCategoryRow, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.Name, arg.Slug, arg.SortOrder)
	var i CreateCategoryRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.SortOrder,
		&i.IsActive,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (category_id, name, slug, description, assignment_mode, estimated_minutes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, category_id, name, slug, description, assignment_mode, estimated_minutes, is_active
`

type CreateServiceParams struct {
	CategoryID       uuid.UUID
	Name             string
	Slug             string
	Description      string
	AssignmentMode   string
	EstimatedMinutes int32
}

type CreateServiceRow struct {
	ID               uuid.UUID
	CategoryID       uuid.UUID
	Name             string
	Slug             string
	Description      string
	AssignmentMode   string
	EstimatedMinutes int32
	IsActive         bool
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (CreateServiceRow, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.AssignmentMode,
		arg.EstimatedMinutes,
	)
	var i CreateServiceRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AssignmentMode,
		&i.EstimatedMinutes,
		&i.IsActive,
	)
	return i, err
}

const createVariant = `-- name: CreateVariant :one
INSERT INTO service_variants (service_id, name, base_price_paise)
VALUES ($1, $2, $3)
RETURNING id, service_id, name, base_price_paise, is_active
`

type CreateVariantParams struct {
	ServiceID      uuid.UUID
	Name           string
	BasePricePaise money.Money
}

type CreateVariantRow struct {
	ID             uuid.UUID
	ServiceID      uuid.UUID
	Name           string
	BasePricePaise money.Money
	IsActive       bool
}

func (q *Queries) CreateVariant(ctx context.Context, arg CreateVariantParams) (CreateVariantRow, error) {
	row := q.db.QueryRow(ctx, createVariant, arg.ServiceID, arg.Name, arg.BasePricePaise)
	var i CreateVariantRow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.BasePricePaise,
		&i.IsActive,
	)
	return i, err
}

const getService = `-- name: GetService :one
SELECT id, category_id, name, slug, description, assignment_mode, estimated_minutes, is_active
  FROM services
 WHERE id = $1
`

type GetServiceRow struct {
	ID               uuid.UUID
	CategoryID       uuid.UUID
	Name             string
	Slug             string
	Description      string
	AssignmentMode   string
	EstimatedMinutes int32
	IsActive         bool
}

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (GetServiceRow, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i GetServiceRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.AssignmentMode,
		&i.EstimatedMinutes,
		&i.IsActive,
	)
	return i, err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT id, name, slug, sort_order
  FROM categories
 WHERE is_active
 ORDER BY sort_order, name
`

type ListActiveCategoriesRow struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	SortOrder int32
}

func (q *Queries) ListActiveCategories(ctx context.Context) ([]ListActiveCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCategoriesRow{}
	for rows.Next() {
		var i ListActiveCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveServices = `-- name: ListActiveServices :many
SELECT id, category_id, name, slug, description, assignment_mode, estimated_minutes
  FROM services
 WHERE is_active
 ORDER BY name
`

type ListActiveServicesRow struct {
	ID               uuid.UUID
	CategoryID       uuid.UUID
	Name             string
	Slug             string
	Description      string
	AssignmentMode   string
	EstimatedMinutes int32
}

func (q *Queries) ListActiveServices(ctx context.Context) ([]ListActiveServicesRow, error) {
	rows, err := q.db.Query(ctx, listActiveServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveServicesRow{}
	for rows.Next() {
		var i ListActiveServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.AssignmentMode,
			&i.EstimatedMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVariants = `-- name: ListActiveVariants :many
SELECT v.id, v.service_id, v.name, v.base_price_paise
  FROM service_variants v
  JOIN services s ON s.id = v.service_id
 WHERE v.is_active AND s.is_active
 ORDER BY v.base_price_paise
`

type ListActiveVariantsRow struct {
	ID             uuid.UUID
	ServiceID      uuid.UUID
	Name           string
	BasePricePaise money.Money
}

// Every active variant of an active service, so the browse endpoint can group them by
// service in Go with a single query rather than one per service.
func (q *Queries) ListActiveVariants(ctx context.Context) ([]ListActiveVariantsRow, error) {
	rows, err := q.db.Query(ctx, listActiveVariants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveVariantsRow{}
	for rows.Next() {
		var i ListActiveVariantsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.BasePricePaise,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByService = `-- name: ListQuestionsByService :many
SELECT id, prompt, kind, options, is_required, sort_order
  FROM question_defs
 WHERE service_id = $1
 ORDER BY sort_order
`

type ListQuestionsByServiceRow struct {
	ID         uuid.UUID
	Prompt     string
	Kind       string
	Options    []string
	IsRequired bool
	SortOrder  int32
}

func (q *Queries) ListQuestionsByService(ctx context.Context, serviceID uuid.UUID) ([]ListQuestionsByServiceRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListQuestionsByServiceRow{}
	for rows.Next() {
		var i ListQuestionsByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.Prompt,
			&i.Kind,
			&i.Options,
			&i.IsRequired,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByService = `-- name: ListVariantsByService :many
SELECT id, service_id, name, base_price_paise
  FROM service_variants
 WHERE service_id = $1 AND is_active
 ORDER BY base_price_paise
`

type ListVariantsByServiceRow struct {
	ID             uuid.UUID
	ServiceID      uuid.UUID
	Name           string
	BasePricePaise money.Money
}

func (q *Queries) ListVariantsByService(ctx context.Context, serviceID uuid.UUID) ([]ListVariantsByServiceRow, error) {
	rows, err := q.db.Query(ctx, listVariantsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVariantsByServiceRow{}
	for rows.Next() {
		var i ListVariantsByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.BasePricePaise,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
