// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOtpChallenge = `-- name: ConsumeOtpChallenge :exec
UPDATE otp_challenges
   SET consumed_at = now(), updated_at = now()
 WHERE id = $1
`

func (q *Queries) ConsumeOtpChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOtpChallenge, id)
	return err
}

const countRecentOtpChallenges = `-- name: CountRecentOtpChallenges :one
SELECT count(*)
  FROM otp_challenges
 WHERE phone = $1
   AND purpose = $2
   AND created_at > now() - make_interval(secs => $3)
`

type CountRecentOtpChallengesParams struct {
	Phone         string
	Purpose       string
	WithinSeconds float64
}

// Rate-limit guard: how many challenges were issued for this phone in the last N seconds.
func (q *Queries) CountRecentOtpChallenges(ctx context.Context, arg CountRecentOtpChallengesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentOtpChallenges, arg.Phone, arg.Purpose, arg.WithinSeconds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (phone, name, role)
VALUES ($1, $2, $3)
RETURNING id, phone, name, role, is_active
`

type CreateUserParams struct {
	Phone string
	Name  string
	Role  string
}

type CreateUserRow struct {
	ID       uuid.UUID
	Phone    string
	Name     string
	Role     string
	IsActive bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Phone, arg.Name, arg.Role)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const getLiveOtpChallenge = `-- name: GetLiveOtpChallenge :one
SELECT id, code_hash, attempts, max_attempts
  FROM otp_challenges
 WHERE phone = $1
   AND purpose = $2
   AND consumed_at IS NULL
   AND expires_at > now()
 ORDER BY created_at DESC
 LIMIT 1
`

type GetLiveOtpChallengeParams struct {
	Phone   string
	Purpose string
}

type GetLiveOtpChallengeRow struct {
	ID          uuid.UUID
	CodeHash    string
	Attempts    int32
	MaxAttempts int32
}

// The most recent challenge for this phone and purpose that is still usable: not consumed,
// not expired. Uses the partial index otp_challenges_live_idx.
func (q *Queries) GetLiveOtpChallenge(ctx context.Context, arg GetLiveOtpChallengeParams) (GetLiveOtpChallengeRow, error) {
	row := q.db.QueryRow(ctx, getLiveOtpChallenge, arg.Phone, arg.Purpose)
	var i GetLiveOtpChallengeRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, name, role, is_active
  FROM users
 WHERE phone = $1
`

type GetUserByPhoneRow struct {
	ID       uuid.UUID
	Phone    string
	Name     string
	Role     string
	IsActive bool
}

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (GetUserByPhoneRow, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i GetUserByPhoneRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const incrementOtpAttempts = `-- name: IncrementOtpAttempts :exec
UPDATE otp_challenges
   SET attempts = attempts + 1, updated_at = now()
 WHERE id = $1
`

func (q *Queries) IncrementOtpAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOtpAttempts, id)
	return err
}

const insertOtpChallenge = `-- name: InsertOtpChallenge :one
INSERT INTO otp_challenges (purpose, phone, code_hash, expires_at, max_attempts)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertOtpChallengeParams struct {
	Purpose     string
	Phone       string
	CodeHash    string
	ExpiresAt   pgtype.Timestamptz
	MaxAttempts int32
}

// purpose is LOGIN here, so booking_id stays NULL — the CHECK
// otp_challenges_purpose_matches_booking enforces exactly that.
func (q *Queries) InsertOtpChallenge(ctx context.Context, arg InsertOtpChallengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertOtpChallenge,
		arg.Purpose,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.MaxAttempts,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const recomputeTechnicianRating = `-- name: RecomputeTechnicianRating :exec
UPDATE technicians
   SET rating = COALESCE((SELECT AVG(rating)::numeric(3, 2) FROM reviews WHERE technician_id = $1), 5.00),
       updated_at = now()
 WHERE user_id = $1
`

// Recompute a technician's rating as the average of all their reviews. Idempotent — the
// review.submitted consumer can run it as often as the event is delivered.
func (q *Queries) RecomputeTechnicianRating(ctx context.Context, technicianID uuid.UUID) error {
	_, err := q.db.Exec(ctx, recomputeTechnicianRating, technicianID)
	return err
}

const scrubUser = `-- name: ScrubUser :exec
UPDATE users
   SET name = 'Deleted user',
       phone = $1,
       deleted_at = now()
 WHERE id = $2 AND deleted_at IS NULL
`

type ScrubUserParams struct {
	ScrubbedPhone string
	ID            uuid.UUID
}

// Account deletion: anonymise the user in place (we cannot hard-delete — see migration 00012).
// Scrubs the PII and marks the account deleted; the scrubbed phone stays unique and frees the
// real number for re-registration.
func (q *Queries) ScrubUser(ctx context.Context, arg ScrubUserParams) error {
	_, err := q.db.Exec(ctx, scrubUser, arg.ScrubbedPhone, arg.ID)
	return err
}
