// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kokkondaBhanuteja/sethu-care/internal/money"
)

const completionLedgerExists = `-- name: CompletionLedgerExists :one
SELECT EXISTS (
  SELECT 1 FROM ledger_entries
   WHERE (order_id = $1 AND kind = 'REVENUE')
      OR (booking_id = $2 AND kind = 'CASH_CUSTODY')
) AS exists
`

type CompletionLedgerExistsParams struct {
	OrderID   *uuid.UUID
	BookingID *uuid.UUID
}

// Idempotency guard for the booking.completed consumer: has this booking already been billed?
// REVENUE attaches to the order; CASH_CUSTODY to the booking. In P1 an order has one booking,
// so either presence means "already recorded".
func (q *Queries) CompletionLedgerExists(ctx context.Context, arg CompletionLedgerExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, completionLedgerExists, arg.OrderID, arg.BookingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const creditExistsForOrder = `-- name: CreditExistsForOrder :one
SELECT EXISTS (
  SELECT 1 FROM ledger_entries WHERE order_id = $1 AND kind = 'CREDIT_ISSUED'
) AS exists
`

// Idempotency guard for the failed-booking credit consumer.
func (q *Queries) CreditExistsForOrder(ctx context.Context, orderID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, creditExistsForOrder, orderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const depositExistsForBooking = `-- name: DepositExistsForBooking :one
SELECT EXISTS (
  SELECT 1 FROM ledger_entries WHERE booking_id = $1 AND kind = 'CASH_DEPOSIT'
) AS exists
`

func (q *Queries) DepositExistsForBooking(ctx context.Context, bookingID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, depositExistsForBooking, bookingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBookingCashCustody = `-- name: GetBookingCashCustody :one
SELECT amount_paise, technician_id
  FROM ledger_entries
 WHERE booking_id = $1 AND kind = 'CASH_CUSTODY'
 LIMIT 1
`

type GetBookingCashCustodyRow struct {
	AmountPaise  money.Money
	TechnicianID *uuid.UUID
}

// The cash a technician is holding for a booking (the CASH_CUSTODY row), so a deposit can
// match its amount and be attributed to the right technician.
func (q *Queries) GetBookingCashCustody(ctx context.Context, bookingID *uuid.UUID) (GetBookingCashCustodyRow, error) {
	row := q.db.QueryRow(ctx, getBookingCashCustody, bookingID)
	var i GetBookingCashCustodyRow
	err := row.Scan(&i.AmountPaise, &i.TechnicianID)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (kind, amount_paise, order_id, booking_id, customer_id, technician_id, method, memo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLedgerEntryParams struct {
	Kind         string
	AmountPaise  money.Money
	OrderID      *uuid.UUID
	BookingID    *uuid.UUID
	CustomerID   *uuid.UUID
	TechnicianID *uuid.UUID
	Method       *string
	Memo         string
}

// One append-only row. The database CHECK enforces the attach rules (REVENUE -> order,
// CASH_CUSTODY -> booking + technician + method=CASH), so a malformed entry is rejected here,
// not discovered later.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.Kind,
		arg.AmountPaise,
		arg.OrderID,
		arg.BookingID,
		arg.CustomerID,
		arg.TechnicianID,
		arg.Method,
		arg.Memo,
	)
	return err
}

const listCashReconciliation = `-- name: ListCashReconciliation :many
SELECT
  position.technician_id, u.name,
  position.collected_paise, position.deposited_paise, position.outstanding_paise,
  position.oldest_collection_at::timestamptz AS oldest_collection_at
FROM technician_cash_position position
JOIN users u ON u.id = position.technician_id
WHERE position.outstanding_paise > 0
ORDER BY position.oldest_collection_at
`

type ListCashReconciliationRow struct {
	TechnicianID       *uuid.UUID
	Name               string
	CollectedPaise     money.Money
	DepositedPaise     money.Money
	OutstandingPaise   money.Money
	OldestCollectionAt pgtype.Timestamptz
}

// The admin reconciliation view: every technician who still owes a deposit, oldest first.
func (q *Queries) ListCashReconciliation(ctx context.Context) ([]ListCashReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listCashReconciliation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCashReconciliationRow{}
	for rows.Next() {
		var i ListCashReconciliationRow
		if err := rows.Scan(
			&i.TechnicianID,
			&i.Name,
			&i.CollectedPaise,
			&i.DepositedPaise,
			&i.OutstandingPaise,
			&i.OldestCollectionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
