// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/kokkondaBhanuteja/sethu-care/internal/money"
)

const completionLedgerExists = `-- name: CompletionLedgerExists :one
SELECT EXISTS (
  SELECT 1 FROM ledger_entries
   WHERE (order_id = $1 AND kind = 'REVENUE')
      OR (booking_id = $2 AND kind = 'CASH_CUSTODY')
) AS exists
`

type CompletionLedgerExistsParams struct {
	OrderID   *uuid.UUID
	BookingID *uuid.UUID
}

// Idempotency guard for the booking.completed consumer: has this booking already been billed?
// REVENUE attaches to the order; CASH_CUSTODY to the booking. In P1 an order has one booking,
// so either presence means "already recorded".
func (q *Queries) CompletionLedgerExists(ctx context.Context, arg CompletionLedgerExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, completionLedgerExists, arg.OrderID, arg.BookingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const creditExistsForOrder = `-- name: CreditExistsForOrder :one
SELECT EXISTS (
  SELECT 1 FROM ledger_entries WHERE order_id = $1 AND kind = 'CREDIT_ISSUED'
) AS exists
`

// Idempotency guard for the failed-booking credit consumer.
func (q *Queries) CreditExistsForOrder(ctx context.Context, orderID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, creditExistsForOrder, orderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (kind, amount_paise, order_id, booking_id, customer_id, technician_id, method, memo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLedgerEntryParams struct {
	Kind         string
	AmountPaise  money.Money
	OrderID      *uuid.UUID
	BookingID    *uuid.UUID
	CustomerID   *uuid.UUID
	TechnicianID *uuid.UUID
	Method       *string
	Memo         string
}

// One append-only row. The database CHECK enforces the attach rules (REVENUE -> order,
// CASH_CUSTODY -> booking + technician + method=CASH), so a malformed entry is rejected here,
// not discovered later.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.Kind,
		arg.AmountPaise,
		arg.OrderID,
		arg.BookingID,
		arg.CustomerID,
		arg.TechnicianID,
		arg.Method,
		arg.Memo,
	)
	return err
}
