// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getNotificationRecipient = `-- name: GetNotificationRecipient :one
SELECT u.id, u.name, u.phone
  FROM bookings b
  JOIN users u ON u.id = b.customer_id
 WHERE b.id = $1
`

type GetNotificationRecipientRow struct {
	ID    uuid.UUID
	Name  string
	Phone string
}

// For a booking event, the recipient is the customer.
func (q *Queries) GetNotificationRecipient(ctx context.Context, id uuid.UUID) (GetNotificationRecipientRow, error) {
	row := q.db.QueryRow(ctx, getNotificationRecipient, id)
	var i GetNotificationRecipientRow
	err := row.Scan(&i.ID, &i.Name, &i.Phone)
	return i, err
}

const insertNotification = `-- name: InsertNotification :execrows
INSERT INTO notification_log (recipient_id, channel, event_type, booking_id, body)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (booking_id, event_type) WHERE booking_id IS NOT NULL DO NOTHING
`

type InsertNotificationParams struct {
	RecipientID uuid.UUID
	Channel     string
	EventType   string
	BookingID   *uuid.UUID
	Body        string
}

// ON CONFLICT DO NOTHING against the (booking_id, event_type) unique index makes this
// idempotent: a redelivered event inserts nothing and returns 0 rows affected. No duplicate
// SMS on a redelivery.
func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertNotification,
		arg.RecipientID,
		arg.Channel,
		arg.EventType,
		arg.BookingID,
		arg.Body,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
