// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const fetchUnpublishedOutbox = `-- name: FetchUnpublishedOutbox :many
SELECT id, aggregate_type, aggregate_id, event_type, payload, attempts
  FROM outbox
 WHERE published_at IS NULL
 ORDER BY created_at
 LIMIT $1
`

type FetchUnpublishedOutboxRow struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Attempts      int32
}

// What the publisher worker reads: everything not yet sent, oldest first. Uses the partial
// index outbox_unpublished_idx, so it stays fast no matter how many events have been sent.
func (q *Queries) FetchUnpublishedOutbox(ctx context.Context, limit int32) ([]FetchUnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, fetchUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FetchUnpublishedOutboxRow{}
	for rows.Next() {
		var i FetchUnpublishedOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox (aggregate_type, aggregate_id, event_type, payload)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxEventParams struct {
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
}

// The transactional outbox (ROADMAP §8). Inserted in the SAME transaction as the state
// change it describes — so either both land or neither does, and a crash between "booking
// completed" and "ledger notified" cannot lose the event. Delivery is at-least-once; every
// consumer must be idempotent.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
	)
	return err
}
