// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kokkondaBhanuteja/sethu-care/internal/money"
)

const getPaymentByBooking = `-- name: GetPaymentByBooking :one
SELECT
  p.id, p.booking_id, p.order_id, p.amount_paise, p.reference, p.status,
  p.provider_ref, p.created_at, p.captured_at,
  b.customer_id, b.technician_id
FROM payments p
JOIN bookings b ON b.id = p.booking_id
WHERE p.booking_id = $1
`

type GetPaymentByBookingRow struct {
	ID           uuid.UUID
	BookingID    uuid.UUID
	OrderID      uuid.UUID
	AmountPaise  money.Money
	Reference    string
	Status       string
	ProviderRef  *string
	CreatedAt    pgtype.Timestamptz
	CapturedAt   pgtype.Timestamptz
	CustomerID   uuid.UUID
	TechnicianID *uuid.UUID
}

// The collection for a booking, joined to the booking's parties so the caller can authorize a
// read (the owning customer or the assigned technician may see the QR).
func (q *Queries) GetPaymentByBooking(ctx context.Context, bookingID uuid.UUID) (GetPaymentByBookingRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByBooking, bookingID)
	var i GetPaymentByBookingRow
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.AmountPaise,
		&i.Reference,
		&i.Status,
		&i.ProviderRef,
		&i.CreatedAt,
		&i.CapturedAt,
		&i.CustomerID,
		&i.TechnicianID,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, booking_id, order_id, amount_paise, reference, status, provider_ref, created_at, captured_at
FROM payments
WHERE reference = $1
`

func (q *Queries) GetPaymentByReference(ctx context.Context, reference string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, reference)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.AmountPaise,
		&i.Reference,
		&i.Status,
		&i.ProviderRef,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}

const listPendingPayments = `-- name: ListPendingPayments :many
SELECT reference, booking_id, amount_paise, status, created_at
FROM payments
WHERE status = 'PENDING'
ORDER BY created_at
`

type ListPendingPaymentsRow struct {
	Reference   string
	BookingID   uuid.UUID
	AmountPaise money.Money
	Status      string
	CreatedAt   pgtype.Timestamptz
}

// Every UPI collection still awaiting capture, oldest first — the ops payments queue. In production
// the PSP webhook captures these; the console lets an admin confirm one by hand in P1.
func (q *Queries) ListPendingPayments(ctx context.Context) ([]ListPendingPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listPendingPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingPaymentsRow{}
	for rows.Next() {
		var i ListPendingPaymentsRow
		if err := rows.Scan(
			&i.Reference,
			&i.BookingID,
			&i.AmountPaise,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentCaptured = `-- name: MarkPaymentCaptured :exec
UPDATE payments
   SET status = 'CAPTURED', provider_ref = $1, captured_at = now()
 WHERE reference = $2 AND status = 'PENDING'
`

type MarkPaymentCapturedParams struct {
	ProviderRef *string
	Reference   string
}

// Move a collection PENDING -> CAPTURED. The WHERE status = 'PENDING' makes a double capture a
// no-op at the row level; the caller pairs this with the REVENUE insert in one transaction.
func (q *Queries) MarkPaymentCaptured(ctx context.Context, arg MarkPaymentCapturedParams) error {
	_, err := q.db.Exec(ctx, markPaymentCaptured, arg.ProviderRef, arg.Reference)
	return err
}

const upsertPendingPayment = `-- name: UpsertPendingPayment :one
INSERT INTO payments (booking_id, order_id, amount_paise, reference)
VALUES ($1, $2, $3, $4)
ON CONFLICT (booking_id) DO UPDATE SET amount_paise = payments.amount_paise
RETURNING id, booking_id, order_id, amount_paise, reference, status, provider_ref, created_at, captured_at
`

type UpsertPendingPaymentParams struct {
	BookingID   uuid.UUID
	OrderID     uuid.UUID
	AmountPaise money.Money
	Reference   string
}

// Create the UPI collection for a booking, or return the existing one. The ON CONFLICT no-op
// update (booking_id is UNIQUE) makes this idempotent: a redelivered booking.completed event
// does not create a second collection, and RETURNING still yields the row either way.
func (q *Queries) UpsertPendingPayment(ctx context.Context, arg UpsertPendingPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, upsertPendingPayment,
		arg.BookingID,
		arg.OrderID,
		arg.AmountPaise,
		arg.Reference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrderID,
		&i.AmountPaise,
		&i.Reference,
		&i.Status,
		&i.ProviderRef,
		&i.CreatedAt,
		&i.CapturedAt,
	)
	return i, err
}
