// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photos.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertWorkPhoto = `-- name: InsertWorkPhoto :exec
INSERT INTO work_photos (booking_id, uploaded_by, kind, url)
VALUES ($1, $2, $3, $4)
`

type InsertWorkPhotoParams struct {
	BookingID  uuid.UUID
	UploadedBy uuid.UUID
	Kind       string
	Url        string
}

// Record one uploaded work photo (the URL of a file already on the CDN). The bytes are on
// Cloudinary; this row is the durable pointer and its provenance (who, which booking, when).
func (q *Queries) InsertWorkPhoto(ctx context.Context, arg InsertWorkPhotoParams) error {
	_, err := q.db.Exec(ctx, insertWorkPhoto,
		arg.BookingID,
		arg.UploadedBy,
		arg.Kind,
		arg.Url,
	)
	return err
}

const listWorkPhotosForBooking = `-- name: ListWorkPhotosForBooking :many
SELECT id, booking_id, uploaded_by, kind, url, created_at
FROM work_photos
WHERE booking_id = $1
ORDER BY kind, created_at
`

// Every photo for a booking, oldest first, BEFORE grouped ahead of AFTER.
func (q *Queries) ListWorkPhotosForBooking(ctx context.Context, bookingID uuid.UUID) ([]WorkPhoto, error) {
	rows, err := q.db.Query(ctx, listWorkPhotosForBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkPhoto{}
	for rows.Next() {
		var i WorkPhoto
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.UploadedBy,
			&i.Kind,
			&i.Url,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
