// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertReview = `-- name: InsertReview :one
INSERT INTO reviews (booking_id, customer_id, technician_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertReviewParams struct {
	BookingID    uuid.UUID
	CustomerID   uuid.UUID
	TechnicianID uuid.UUID
	Rating       int32
	Comment      string
}

// One review per booking (the UNIQUE index on booking_id enforces it; a second attempt is a
// 23505 the service turns into "already reviewed").
func (q *Queries) InsertReview(ctx context.Context, arg InsertReviewParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertReview,
		arg.BookingID,
		arg.CustomerID,
		arg.TechnicianID,
		arg.Rating,
		arg.Comment,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
