// Tailwind / NativeWind preset — the "Indigo Velvet" tokens as utility classes, lifted from the
// Stitch screen configs so class names (`bg-primary`, `text-on-surface`, `rounded-card`,
// `px-mobile-margin`, `text-body-md`) match the mockups exactly. Shared by both RN apps (NativeWind)
// and the admin web (Tailwind). Values mirror packages/tokens/src/primitives.ts — keep them in sync.

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // "Blue Harbour" — solid blue primary + teal accent on white, near-black text. No gradients.
        // WCAG AA at all sizes: dark text ~15:1, blue/teal action colours 4.5–6:1 with white.
        primary: "#1d4ed8",
        "on-primary": "#ffffff",
        "primary-container": "#dbeafe",
        "on-primary-container": "#1e40af",
        "primary-fixed": "#bfdbfe",
        "primary-fixed-dim": "#93c5fd",
        "on-primary-fixed": "#172554",
        "on-primary-fixed-variant": "#1e40af",
        "inverse-primary": "#93c5fd",
        "surface-tint": "#1d4ed8",
        secondary: "#0d9488",
        "on-secondary": "#ffffff",
        "secondary-container": "#ccfbf1",
        "on-secondary-container": "#115e59",
        "secondary-fixed": "#99f6e4",
        "secondary-fixed-dim": "#5eead4",
        "on-secondary-fixed": "#042f2e",
        "on-secondary-fixed-variant": "#115e59",
        tertiary: "#15803d",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#dcfce7",
        "on-tertiary-container": "#166534",
        "tertiary-fixed": "#bbf7d0",
        "tertiary-fixed-dim": "#86efac",
        "on-tertiary-fixed": "#052e16",
        "on-tertiary-fixed-variant": "#166534",
        error: "#dc2626",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#991b1b",
        background: "#ffffff",
        "on-background": "#0f172a",
        surface: "#ffffff",
        "surface-dim": "#e2e8f0",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f8fafc",
        "surface-container": "#f1f5f9",
        "surface-container-high": "#e2e8f0",
        "surface-container-highest": "#cbd5e1",
        "on-surface": "#0f172a",
        "on-surface-variant": "#475569",
        "surface-variant": "#e2e8f0",
        "inverse-surface": "#1e293b",
        "inverse-on-surface": "#f1f5f9",
        outline: "#94a3b8",
        "outline-variant": "#e2e8f0",
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        DEFAULT: "4px",
        md: "8px",
        lg: "8px",
        xl: "12px",
        card: "24px",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "32px",
        xl: "48px",
        gutter: "24px",
        "mobile-margin": "20px",
        "container-max": "1280px",
      },
      fontFamily: {
        // Inter, per weight (each weight is its own RN family). Loaded via @expo-google-fonts/inter.
        display: ["Inter_800ExtraBold"],
        heading: ["Inter_700Bold"],
        semibold: ["Inter_600SemiBold"],
        medium: ["Inter_500Medium"],
        body: ["Inter_400Regular"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-md": ["30px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
      },
    },
  },
};
