// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: address.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const clearDefaultAddresses = `-- name: ClearDefaultAddresses :exec
UPDATE addresses SET is_default = false, updated_at = now()
 WHERE user_id = $1 AND is_default
`

// Unset the current default before setting a new one, so the partial unique index
// addresses_one_default_per_user_idx is never violated mid-transaction.
func (q *Queries) ClearDefaultAddresses(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultAddresses, userID)
	return err
}

const countAddressesByUser = `-- name: CountAddressesByUser :one
SELECT count(*) FROM addresses WHERE user_id = $1
`

func (q *Queries) CountAddressesByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressesByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAddress = `-- name: CreateAddress :one
INSERT INTO addresses (user_id, label, line1, line2, city, pincode, geog, is_default)
VALUES (
  $1, $2, $3, $4, $5, $6,
  ST_SetSRID(ST_MakePoint($7::float8, $8::float8), 4326)::geography,
  $9
)
RETURNING id, label, line1, line2, city, pincode, is_default
`

type CreateAddressParams struct {
	UserID    uuid.UUID
	Label     string
	Line1     string
	Line2     string
	City      string
	Pincode   string
	Lng       float64
	Lat       float64
	IsDefault bool
}

type CreateAddressRow struct {
	ID        uuid.UUID
	Label     string
	Line1     string
	Line2     string
	City      string
	Pincode   string
	IsDefault bool
}

// The point comes in as lat/lng (the customer app has device GPS); we build the geography
// here. RETURNING only scalar columns keeps sqlc away from the geography type.
func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (CreateAddressRow, error) {
	row := q.db.QueryRow(ctx, createAddress,
		arg.UserID,
		arg.Label,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.Pincode,
		arg.Lng,
		arg.Lat,
		arg.IsDefault,
	)
	var i CreateAddressRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Line1,
		&i.Line2,
		&i.City,
		&i.Pincode,
		&i.IsDefault,
	)
	return i, err
}

const listAddressesByUser = `-- name: ListAddressesByUser :many
SELECT
  id, label, line1, line2, city, pincode, is_default,
  ST_Y(geog::geometry)::float8 AS lat,
  ST_X(geog::geometry)::float8 AS lng
FROM addresses
WHERE user_id = $1
ORDER BY is_default DESC, created_at DESC
`

type ListAddressesByUserRow struct {
	ID        uuid.UUID
	Label     string
	Line1     string
	Line2     string
	City      string
	Pincode   string
	IsDefault bool
	Lat       float64
	Lng       float64
}

// ST_Y/ST_X pull latitude/longitude back out as plain floats, so sqlc never sees the
// geography type in the result.
func (q *Queries) ListAddressesByUser(ctx context.Context, userID uuid.UUID) ([]ListAddressesByUserRow, error) {
	rows, err := q.db.Query(ctx, listAddressesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddressesByUserRow{}
	for rows.Next() {
		var i ListAddressesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.Pincode,
			&i.IsDefault,
			&i.Lat,
			&i.Lng,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
