// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: adminaccount.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeAdminChallenge = `-- name: ConsumeAdminChallenge :exec
UPDATE admin_challenges
   SET consumed_at = now()
 WHERE id = $1
`

func (q *Queries) ConsumeAdminChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeAdminChallenge, id)
	return err
}

const countAdminActivity = `-- name: CountAdminActivity :one
SELECT count(*) AS actions,
       count(*) FILTER (WHERE action = 'ASSIGN') AS bookings_rescued
  FROM audit_logs
 WHERE actor_user_id = $1
`

type CountAdminActivityRow struct {
	Actions         int64
	BookingsRescued int64
}

// The profile scoreboard's honest half: total audited actions by this operator, and how
// many were booking assigns (the rescue action). The rest of the scoreboard has no engine
// yet and stays zero.
func (q *Queries) CountAdminActivity(ctx context.Context, actorUserID *uuid.UUID) (CountAdminActivityRow, error) {
	row := q.db.QueryRow(ctx, countAdminActivity, actorUserID)
	var i CountAdminActivityRow
	err := row.Scan(&i.Actions, &i.BookingsRescued)
	return i, err
}

const countRecentAdminChallenges = `-- name: CountRecentAdminChallenges :one
SELECT count(*) AS issued, min(created_at)::timestamptz AS oldest_at
  FROM admin_challenges
 WHERE admin_account_id = $1
   AND created_at > now() - make_interval(secs => $2::int)
`

type CountRecentAdminChallengesParams struct {
	AdminAccountID uuid.UUID
	WithinSeconds  int32
}

type CountRecentAdminChallengesRow struct {
	Issued   int64
	OldestAt pgtype.Timestamptz
}

// The resend budget: 3 fresh challenges per 10 minutes per account. min(created_at) lets
// the caller compute when the window reopens for the 429's resetAt.
func (q *Queries) CountRecentAdminChallenges(ctx context.Context, arg CountRecentAdminChallengesParams) (CountRecentAdminChallengesRow, error) {
	row := q.db.QueryRow(ctx, countRecentAdminChallenges, arg.AdminAccountID, arg.WithinSeconds)
	var i CountRecentAdminChallengesRow
	err := row.Scan(&i.Issued, &i.OldestAt)
	return i, err
}

const countSignedInAdminDevices = `-- name: CountSignedInAdminDevices :one
SELECT count(*)
  FROM admin_devices
 WHERE admin_account_id = $1
   AND revoked_at IS NULL
   AND signed_in
`

// activeSessions on the security screen. Session bookkeeping, not token revocation — the
// JWTs themselves are stateless.
func (q *Queries) CountSignedInAdminDevices(ctx context.Context, adminAccountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSignedInAdminDevices, adminAccountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminAccountByEmail = `-- name: GetAdminAccountByEmail :one

SELECT accounts.id, accounts.user_id, accounts.email, accounts.password_hash,
       accounts.display_name, accounts.is_disabled, accounts.failed_login_attempts,
       accounts.locked_until, accounts.password_changed_at, accounts.created_at,
       users.phone, users.name AS user_name
  FROM admin_accounts accounts
  JOIN users ON users.id = accounts.user_id
 WHERE accounts.email = $1
`

type GetAdminAccountByEmailRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Email               string
	PasswordHash        string
	DisplayName         string
	IsDisabled          bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	PasswordChangedAt   pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	Phone               string
	UserName            string
}

// The admin console's account context: accounts, trusted devices, second-factor envelopes,
// settings, and diagnostics. Owned by internal/adminaccount — its service is the only writer
// of these tables.
// The login lookup. Email is stored lowercased; callers lowercase before querying.
func (q *Queries) GetAdminAccountByEmail(ctx context.Context, email string) (GetAdminAccountByEmailRow, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByEmail, email)
	var i GetAdminAccountByEmailRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsDisabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Phone,
		&i.UserName,
	)
	return i, err
}

const getAdminAccountByID = `-- name: GetAdminAccountByID :one
SELECT accounts.id, accounts.user_id, accounts.email, accounts.password_hash,
       accounts.display_name, accounts.is_disabled, accounts.failed_login_attempts,
       accounts.locked_until, accounts.password_changed_at, accounts.created_at,
       users.phone, users.name AS user_name
  FROM admin_accounts accounts
  JOIN users ON users.id = accounts.user_id
 WHERE accounts.id = $1
`

type GetAdminAccountByIDRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Email               string
	PasswordHash        string
	DisplayName         string
	IsDisabled          bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	PasswordChangedAt   pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	Phone               string
	UserName            string
}

// The challenge-holder lookup during the second factor, before any session exists.
func (q *Queries) GetAdminAccountByID(ctx context.Context, id uuid.UUID) (GetAdminAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByID, id)
	var i GetAdminAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsDisabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Phone,
		&i.UserName,
	)
	return i, err
}

const getAdminAccountByUserID = `-- name: GetAdminAccountByUserID :one
SELECT accounts.id, accounts.user_id, accounts.email, accounts.password_hash,
       accounts.display_name, accounts.is_disabled, accounts.failed_login_attempts,
       accounts.locked_until, accounts.password_changed_at, accounts.created_at,
       users.phone, users.name AS user_name
  FROM admin_accounts accounts
  JOIN users ON users.id = accounts.user_id
 WHERE accounts.user_id = $1
`

type GetAdminAccountByUserIDRow struct {
	ID                  uuid.UUID
	UserID              uuid.UUID
	Email               string
	PasswordHash        string
	DisplayName         string
	IsDisabled          bool
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
	PasswordChangedAt   pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	Phone               string
	UserName            string
}

// The token-holder lookup: every operation behind the bearer middleware knows only the
// users.id the token names.
func (q *Queries) GetAdminAccountByUserID(ctx context.Context, userID uuid.UUID) (GetAdminAccountByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminAccountByUserID, userID)
	var i GetAdminAccountByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.IsDisabled,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.Phone,
		&i.UserName,
	)
	return i, err
}

const getAdminChallengeForResend = `-- name: GetAdminChallengeForResend :one
SELECT id, admin_account_id, device_id, device_name, attempts, max_attempts, expires_at
  FROM admin_challenges
 WHERE id = $1
   AND consumed_at IS NULL
`

type GetAdminChallengeForResendRow struct {
	ID             uuid.UUID
	AdminAccountID uuid.UUID
	DeviceID       string
	DeviceName     string
	Attempts       int32
	MaxAttempts    int32
	ExpiresAt      pgtype.Timestamptz
}

// Resend accepts an EXPIRED envelope (the expired screen's primary action is Resend) but
// never a consumed one — a completed sign-in cannot mint fresh codes.
func (q *Queries) GetAdminChallengeForResend(ctx context.Context, id uuid.UUID) (GetAdminChallengeForResendRow, error) {
	row := q.db.QueryRow(ctx, getAdminChallengeForResend, id)
	var i GetAdminChallengeForResendRow
	err := row.Scan(
		&i.ID,
		&i.AdminAccountID,
		&i.DeviceID,
		&i.DeviceName,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
	)
	return i, err
}

const getAdminDeviceByID = `-- name: GetAdminDeviceByID :one
SELECT id, device_id, name, device_type, location, trusted_until, signed_in, last_used_at,
       revoked_at
  FROM admin_devices
 WHERE id = $1
   AND admin_account_id = $2
`

type GetAdminDeviceByIDParams struct {
	ID             uuid.UUID
	AdminAccountID uuid.UUID
}

type GetAdminDeviceByIDRow struct {
	ID           uuid.UUID
	DeviceID     string
	Name         string
	DeviceType   string
	Location     string
	TrustedUntil pgtype.Timestamptz
	SignedIn     bool
	LastUsedAt   pgtype.Timestamptz
	RevokedAt    pgtype.Timestamptz
}

func (q *Queries) GetAdminDeviceByID(ctx context.Context, arg GetAdminDeviceByIDParams) (GetAdminDeviceByIDRow, error) {
	row := q.db.QueryRow(ctx, getAdminDeviceByID, arg.ID, arg.AdminAccountID)
	var i GetAdminDeviceByIDRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.DeviceType,
		&i.Location,
		&i.TrustedUntil,
		&i.SignedIn,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAdminDiagnosticsByKey = `-- name: GetAdminDiagnosticsByKey :one
SELECT id, submitted_at
  FROM admin_diagnostics
 WHERE admin_account_id = $1
   AND idempotency_key = $2
`

type GetAdminDiagnosticsByKeyParams struct {
	AdminAccountID uuid.UUID
	IdempotencyKey string
}

type GetAdminDiagnosticsByKeyRow struct {
	ID          uuid.UUID
	SubmittedAt pgtype.Timestamptz
}

// The idempotent replay read: the same Idempotency-Key returns the first receipt.
func (q *Queries) GetAdminDiagnosticsByKey(ctx context.Context, arg GetAdminDiagnosticsByKeyParams) (GetAdminDiagnosticsByKeyRow, error) {
	row := q.db.QueryRow(ctx, getAdminDiagnosticsByKey, arg.AdminAccountID, arg.IdempotencyKey)
	var i GetAdminDiagnosticsByKeyRow
	err := row.Scan(&i.ID, &i.SubmittedAt)
	return i, err
}

const getAdminSettings = `-- name: GetAdminSettings :one
SELECT admin_account_id, appearance, haptics, default_landing_route,
       channel_sla_at_risk, channel_provider_no_show, channel_zone_supply_critical,
       channel_payment_failure, channel_new_applications, channel_auto_suspensions,
       channel_document_expiring, channel_daily_summary,
       critical_sound, digest_time, quiet_hours_from, quiet_hours_to, quiet_hours_enabled,
       vibrate, biometric_unlock
  FROM admin_settings
 WHERE admin_account_id = $1
`

type GetAdminSettingsRow struct {
	AdminAccountID            uuid.UUID
	Appearance                string
	Haptics                   bool
	DefaultLandingRoute       string
	ChannelSlaAtRisk          bool
	ChannelProviderNoShow     bool
	ChannelZoneSupplyCritical bool
	ChannelPaymentFailure     bool
	ChannelNewApplications    bool
	ChannelAutoSuspensions    bool
	ChannelDocumentExpiring   bool
	ChannelDailySummary       bool
	CriticalSound             string
	DigestTime                string
	QuietHoursFrom            string
	QuietHoursTo              string
	QuietHoursEnabled         bool
	Vibrate                   bool
	BiometricUnlock           bool
}

func (q *Queries) GetAdminSettings(ctx context.Context, adminAccountID uuid.UUID) (GetAdminSettingsRow, error) {
	row := q.db.QueryRow(ctx, getAdminSettings, adminAccountID)
	var i GetAdminSettingsRow
	err := row.Scan(
		&i.AdminAccountID,
		&i.Appearance,
		&i.Haptics,
		&i.DefaultLandingRoute,
		&i.ChannelSlaAtRisk,
		&i.ChannelProviderNoShow,
		&i.ChannelZoneSupplyCritical,
		&i.ChannelPaymentFailure,
		&i.ChannelNewApplications,
		&i.ChannelAutoSuspensions,
		&i.ChannelDocumentExpiring,
		&i.ChannelDailySummary,
		&i.CriticalSound,
		&i.DigestTime,
		&i.QuietHoursFrom,
		&i.QuietHoursTo,
		&i.QuietHoursEnabled,
		&i.Vibrate,
		&i.BiometricUnlock,
	)
	return i, err
}

const getLiveAdminChallenge = `-- name: GetLiveAdminChallenge :one
SELECT id, admin_account_id, device_id, device_name, attempts, max_attempts, expires_at
  FROM admin_challenges
 WHERE id = $1
   AND consumed_at IS NULL
   AND expires_at > now()
`

type GetLiveAdminChallengeRow struct {
	ID             uuid.UUID
	AdminAccountID uuid.UUID
	DeviceID       string
	DeviceName     string
	Attempts       int32
	MaxAttempts    int32
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) GetLiveAdminChallenge(ctx context.Context, id uuid.UUID) (GetLiveAdminChallengeRow, error) {
	row := q.db.QueryRow(ctx, getLiveAdminChallenge, id)
	var i GetLiveAdminChallengeRow
	err := row.Scan(
		&i.ID,
		&i.AdminAccountID,
		&i.DeviceID,
		&i.DeviceName,
		&i.Attempts,
		&i.MaxAttempts,
		&i.ExpiresAt,
	)
	return i, err
}

const getTrustedAdminDevice = `-- name: GetTrustedAdminDevice :one
SELECT id, device_id, name, device_type, location, trusted_until, signed_in, last_used_at
  FROM admin_devices
 WHERE admin_account_id = $1
   AND device_id = $2
   AND revoked_at IS NULL
   AND trusted_until IS NOT NULL
   AND trusted_until > now()
`

type GetTrustedAdminDeviceParams struct {
	AdminAccountID uuid.UUID
	DeviceID       string
}

type GetTrustedAdminDeviceRow struct {
	ID           uuid.UUID
	DeviceID     string
	Name         string
	DeviceType   string
	Location     string
	TrustedUntil pgtype.Timestamptz
	SignedIn     bool
	LastUsedAt   pgtype.Timestamptz
}

// The trusted-device fast path at login: a live trust for this exact device skips the
// second factor.
func (q *Queries) GetTrustedAdminDevice(ctx context.Context, arg GetTrustedAdminDeviceParams) (GetTrustedAdminDeviceRow, error) {
	row := q.db.QueryRow(ctx, getTrustedAdminDevice, arg.AdminAccountID, arg.DeviceID)
	var i GetTrustedAdminDeviceRow
	err := row.Scan(
		&i.ID,
		&i.DeviceID,
		&i.Name,
		&i.DeviceType,
		&i.Location,
		&i.TrustedUntil,
		&i.SignedIn,
		&i.LastUsedAt,
	)
	return i, err
}

const incrementAdminChallengeAttempts = `-- name: IncrementAdminChallengeAttempts :one
UPDATE admin_challenges
   SET attempts = attempts + 1
 WHERE id = $1
RETURNING attempts, max_attempts
`

type IncrementAdminChallengeAttemptsRow struct {
	Attempts    int32
	MaxAttempts int32
}

func (q *Queries) IncrementAdminChallengeAttempts(ctx context.Context, id uuid.UUID) (IncrementAdminChallengeAttemptsRow, error) {
	row := q.db.QueryRow(ctx, incrementAdminChallengeAttempts, id)
	var i IncrementAdminChallengeAttemptsRow
	err := row.Scan(&i.Attempts, &i.MaxAttempts)
	return i, err
}

const insertAdminChallenge = `-- name: InsertAdminChallenge :one
INSERT INTO admin_challenges (admin_account_id, device_id, device_name, max_attempts, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertAdminChallengeParams struct {
	AdminAccountID uuid.UUID
	DeviceID       string
	DeviceName     string
	MaxAttempts    int32
	ExpiresAt      pgtype.Timestamptz
}

// The second-factor envelope. No code here — the code is identity's, in otp_challenges.
func (q *Queries) InsertAdminChallenge(ctx context.Context, arg InsertAdminChallengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAdminChallenge,
		arg.AdminAccountID,
		arg.DeviceID,
		arg.DeviceName,
		arg.MaxAttempts,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertAdminDiagnostics = `-- name: InsertAdminDiagnostics :one
INSERT INTO admin_diagnostics (admin_account_id, idempotency_key, app_version, device_model,
                               os_version, ota_bundle, logs, network_events)
VALUES ($1, $2, $3, $4,
        $5, $6, $7, $8)
RETURNING id, submitted_at
`

type InsertAdminDiagnosticsParams struct {
	AdminAccountID uuid.UUID
	IdempotencyKey string
	AppVersion     string
	DeviceModel    string
	OsVersion      string
	OtaBundle      string
	Logs           []byte
	NetworkEvents  []byte
}

type InsertAdminDiagnosticsRow struct {
	ID          uuid.UUID
	SubmittedAt pgtype.Timestamptz
}

func (q *Queries) InsertAdminDiagnostics(ctx context.Context, arg InsertAdminDiagnosticsParams) (InsertAdminDiagnosticsRow, error) {
	row := q.db.QueryRow(ctx, insertAdminDiagnostics,
		arg.AdminAccountID,
		arg.IdempotencyKey,
		arg.AppVersion,
		arg.DeviceModel,
		arg.OsVersion,
		arg.OtaBundle,
		arg.Logs,
		arg.NetworkEvents,
	)
	var i InsertAdminDiagnosticsRow
	err := row.Scan(&i.ID, &i.SubmittedAt)
	return i, err
}

const listActiveAdminDevices = `-- name: ListActiveAdminDevices :many
SELECT id, device_id, name, device_type, location, trusted_until, signed_in, last_used_at
  FROM admin_devices
 WHERE admin_account_id = $1
   AND revoked_at IS NULL
   AND trusted_until IS NOT NULL
   AND trusted_until > now()
 ORDER BY last_used_at DESC
`

type ListActiveAdminDevicesRow struct {
	ID           uuid.UUID
	DeviceID     string
	Name         string
	DeviceType   string
	Location     string
	TrustedUntil pgtype.Timestamptz
	SignedIn     bool
	LastUsedAt   pgtype.Timestamptz
}

// The trust slots: every unrevoked device with a live trust, most recently used first.
func (q *Queries) ListActiveAdminDevices(ctx context.Context, adminAccountID uuid.UUID) ([]ListActiveAdminDevicesRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdminDevices, adminAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAdminDevicesRow{}
	for rows.Next() {
		var i ListActiveAdminDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.DeviceType,
			&i.Location,
			&i.TrustedUntil,
			&i.SignedIn,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSecurityDevices = `-- name: ListAdminSecurityDevices :many
SELECT id, device_id, name, device_type, location, trusted_until, signed_in, last_used_at
  FROM admin_devices
 WHERE admin_account_id = $1
   AND revoked_at IS NULL
 ORDER BY last_used_at DESC
`

type ListAdminSecurityDevicesRow struct {
	ID           uuid.UUID
	DeviceID     string
	Name         string
	DeviceType   string
	Location     string
	TrustedUntil pgtype.Timestamptz
	SignedIn     bool
	LastUsedAt   pgtype.Timestamptz
}

// The security screen's device rows: every unrevoked device (trusted or session-only),
// most recently used first.
func (q *Queries) ListAdminSecurityDevices(ctx context.Context, adminAccountID uuid.UUID) ([]ListAdminSecurityDevicesRow, error) {
	rows, err := q.db.Query(ctx, listAdminSecurityDevices, adminAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminSecurityDevicesRow{}
	for rows.Next() {
		var i ListAdminSecurityDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.DeviceID,
			&i.Name,
			&i.DeviceType,
			&i.Location,
			&i.TrustedUntil,
			&i.SignedIn,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminSecurityEvents = `-- name: ListAdminSecurityEvents :many
SELECT id, action, created_at, after
  FROM audit_logs
 WHERE entity_type = 'admin_account'
   AND entity_id = $1
   AND action = ANY ($2::text[])
 ORDER BY created_at DESC
 LIMIT $3
`

type ListAdminSecurityEventsParams struct {
	EntityID uuid.UUID
	Actions  []string
	RowLimit int32
}

type ListAdminSecurityEventsRow struct {
	ID        uuid.UUID
	Action    string
	CreatedAt pgtype.Timestamptz
	After     []byte
}

// The recent security events, read back from the audit log the login flows write. The
// device name rides in the audit payload; NULL device means the event named none.
func (q *Queries) ListAdminSecurityEvents(ctx context.Context, arg ListAdminSecurityEventsParams) ([]ListAdminSecurityEventsRow, error) {
	rows, err := q.db.Query(ctx, listAdminSecurityEvents, arg.EntityID, arg.Actions, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminSecurityEventsRow{}
	for rows.Next() {
		var i ListAdminSecurityEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.CreatedAt,
			&i.After,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAdminLoginFailure = `-- name: RecordAdminLoginFailure :one
UPDATE admin_accounts
   SET failed_login_attempts = failed_login_attempts + 1,
       locked_until = CASE
           WHEN failed_login_attempts + 1 >= $1::int
               THEN now() + make_interval(secs => $2::int)
           ELSE locked_until
       END,
       updated_at = now()
 WHERE id = $3
RETURNING failed_login_attempts, locked_until
`

type RecordAdminLoginFailureParams struct {
	MaxAttempts int32
	LockSeconds int32
	ID          uuid.UUID
}

type RecordAdminLoginFailureRow struct {
	FailedLoginAttempts int32
	LockedUntil         pgtype.Timestamptz
}

// One statement so the count and the lock decision cannot race: the caller passes the
// attempt cap and the lock duration, and reads back whether this failure locked the account.
func (q *Queries) RecordAdminLoginFailure(ctx context.Context, arg RecordAdminLoginFailureParams) (RecordAdminLoginFailureRow, error) {
	row := q.db.QueryRow(ctx, recordAdminLoginFailure, arg.MaxAttempts, arg.LockSeconds, arg.ID)
	var i RecordAdminLoginFailureRow
	err := row.Scan(&i.FailedLoginAttempts, &i.LockedUntil)
	return i, err
}

const resetAdminLoginFailures = `-- name: ResetAdminLoginFailures :exec
UPDATE admin_accounts
   SET failed_login_attempts = 0, locked_until = NULL, updated_at = now()
 WHERE id = $1
`

// A successful password verification clears the counter and any lock.
func (q *Queries) ResetAdminLoginFailures(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetAdminLoginFailures, id)
	return err
}

const revokeAdminDevice = `-- name: RevokeAdminDevice :exec
UPDATE admin_devices
   SET revoked_at = now(), trusted_until = NULL, signed_in = false, updated_at = now()
 WHERE id = $1
   AND admin_account_id = $2
   AND revoked_at IS NULL
`

type RevokeAdminDeviceParams struct {
	ID             uuid.UUID
	AdminAccountID uuid.UUID
}

func (q *Queries) RevokeAdminDevice(ctx context.Context, arg RevokeAdminDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeAdminDevice, arg.ID, arg.AdminAccountID)
	return err
}

const setAdminBiometricUnlock = `-- name: SetAdminBiometricUnlock :exec
INSERT INTO admin_settings (admin_account_id, biometric_unlock)
VALUES ($1, $2)
ON CONFLICT (admin_account_id) DO UPDATE
   SET biometric_unlock = EXCLUDED.biometric_unlock,
       updated_at = now(),
       version = admin_settings.version + 1
`

type SetAdminBiometricUnlockParams struct {
	AdminAccountID  uuid.UUID
	BiometricUnlock bool
}

func (q *Queries) SetAdminBiometricUnlock(ctx context.Context, arg SetAdminBiometricUnlockParams) error {
	_, err := q.db.Exec(ctx, setAdminBiometricUnlock, arg.AdminAccountID, arg.BiometricUnlock)
	return err
}

const signOutCurrentAdminDevice = `-- name: SignOutCurrentAdminDevice :one
UPDATE admin_devices
   SET signed_in = false, updated_at = now()
 WHERE id = (SELECT candidate.id
               FROM admin_devices candidate
              WHERE candidate.admin_account_id = $1
                AND candidate.revoked_at IS NULL
                AND candidate.signed_in
              ORDER BY candidate.last_used_at DESC
              LIMIT 1)
RETURNING id
`

// Logout closes the heuristic current session (see TouchCurrentAdminDevice on why it is a
// heuristic).
func (q *Queries) SignOutCurrentAdminDevice(ctx context.Context, adminAccountID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, signOutCurrentAdminDevice, adminAccountID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const touchCurrentAdminDevice = `-- name: TouchCurrentAdminDevice :one
UPDATE admin_devices
   SET last_used_at = now(), updated_at = now()
 WHERE id = (SELECT candidate.id
               FROM admin_devices candidate
              WHERE candidate.admin_account_id = $1
                AND candidate.revoked_at IS NULL
                AND candidate.signed_in
              ORDER BY candidate.last_used_at DESC
              LIMIT 1)
RETURNING id
`

// Best-effort "current device" bookkeeping: tokens are not device-bound (the JWT carries
// only user id + role), so the caller's device is taken to be the account's most recently
// used open session. Used by refresh to keep last_used_at honest.
func (q *Queries) TouchCurrentAdminDevice(ctx context.Context, adminAccountID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, touchCurrentAdminDevice, adminAccountID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertAdminDevice = `-- name: UpsertAdminDevice :one
INSERT INTO admin_devices (admin_account_id, device_id, name, device_type, trusted_until, signed_in, last_used_at)
VALUES ($1, $2, $3, $4,
        CASE WHEN $5::boolean THEN $6::timestamptz ELSE NULL END,
        true, now())
ON CONFLICT (admin_account_id, device_id) DO UPDATE
   SET name = EXCLUDED.name,
       device_type = EXCLUDED.device_type,
       trusted_until = CASE WHEN $5::boolean THEN $6::timestamptz
                            ELSE admin_devices.trusted_until END,
       signed_in = true,
       last_used_at = now(),
       revoked_at = NULL,
       updated_at = now()
RETURNING id, (trusted_until IS NOT NULL)::boolean AS is_trusted
`

type UpsertAdminDeviceParams struct {
	AdminAccountID uuid.UUID
	DeviceID       string
	Name           string
	DeviceType     string
	GrantTrust     bool
	TrustedUntil   pgtype.Timestamptz
}

type UpsertAdminDeviceRow struct {
	ID        uuid.UUID
	IsTrusted bool
}

// A sign-in from a device: refreshes name/last-used, opens its session, clears any old
// revocation (a revoked device that passes a fresh second factor has re-earned its place),
// and grants trust only when asked — never silently dropping an existing trust.
func (q *Queries) UpsertAdminDevice(ctx context.Context, arg UpsertAdminDeviceParams) (UpsertAdminDeviceRow, error) {
	row := q.db.QueryRow(ctx, upsertAdminDevice,
		arg.AdminAccountID,
		arg.DeviceID,
		arg.Name,
		arg.DeviceType,
		arg.GrantTrust,
		arg.TrustedUntil,
	)
	var i UpsertAdminDeviceRow
	err := row.Scan(&i.ID, &i.IsTrusted)
	return i, err
}

const upsertAdminNotificationSettings = `-- name: UpsertAdminNotificationSettings :exec
INSERT INTO admin_settings (admin_account_id,
       channel_sla_at_risk, channel_provider_no_show, channel_zone_supply_critical,
       channel_payment_failure, channel_new_applications, channel_auto_suspensions,
       channel_document_expiring, channel_daily_summary,
       critical_sound, digest_time, quiet_hours_from, quiet_hours_to, quiet_hours_enabled, vibrate)
VALUES ($1,
       $2, $3, $4,
       $5, $6, $7,
       $8, $9,
       $10, $11, $12, $13, $14, $15)
ON CONFLICT (admin_account_id) DO UPDATE
   SET channel_sla_at_risk = EXCLUDED.channel_sla_at_risk,
       channel_provider_no_show = EXCLUDED.channel_provider_no_show,
       channel_zone_supply_critical = EXCLUDED.channel_zone_supply_critical,
       channel_payment_failure = EXCLUDED.channel_payment_failure,
       channel_new_applications = EXCLUDED.channel_new_applications,
       channel_auto_suspensions = EXCLUDED.channel_auto_suspensions,
       channel_document_expiring = EXCLUDED.channel_document_expiring,
       channel_daily_summary = EXCLUDED.channel_daily_summary,
       critical_sound = EXCLUDED.critical_sound,
       digest_time = EXCLUDED.digest_time,
       quiet_hours_from = EXCLUDED.quiet_hours_from,
       quiet_hours_to = EXCLUDED.quiet_hours_to,
       quiet_hours_enabled = EXCLUDED.quiet_hours_enabled,
       vibrate = EXCLUDED.vibrate,
       updated_at = now(),
       version = admin_settings.version + 1
`

type UpsertAdminNotificationSettingsParams struct {
	AdminAccountID            uuid.UUID
	ChannelSlaAtRisk          bool
	ChannelProviderNoShow     bool
	ChannelZoneSupplyCritical bool
	ChannelPaymentFailure     bool
	ChannelNewApplications    bool
	ChannelAutoSuspensions    bool
	ChannelDocumentExpiring   bool
	ChannelDailySummary       bool
	CriticalSound             string
	DigestTime                string
	QuietHoursFrom            string
	QuietHoursTo              string
	QuietHoursEnabled         bool
	Vibrate                   bool
}

func (q *Queries) UpsertAdminNotificationSettings(ctx context.Context, arg UpsertAdminNotificationSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertAdminNotificationSettings,
		arg.AdminAccountID,
		arg.ChannelSlaAtRisk,
		arg.ChannelProviderNoShow,
		arg.ChannelZoneSupplyCritical,
		arg.ChannelPaymentFailure,
		arg.ChannelNewApplications,
		arg.ChannelAutoSuspensions,
		arg.ChannelDocumentExpiring,
		arg.ChannelDailySummary,
		arg.CriticalSound,
		arg.DigestTime,
		arg.QuietHoursFrom,
		arg.QuietHoursTo,
		arg.QuietHoursEnabled,
		arg.Vibrate,
	)
	return err
}

const upsertAdminPreferences = `-- name: UpsertAdminPreferences :exec
INSERT INTO admin_settings (admin_account_id, appearance, haptics, default_landing_route)
VALUES ($1, $2, $3, $4)
ON CONFLICT (admin_account_id) DO UPDATE
   SET appearance = EXCLUDED.appearance,
       haptics = EXCLUDED.haptics,
       default_landing_route = EXCLUDED.default_landing_route,
       updated_at = now(),
       version = admin_settings.version + 1
`

type UpsertAdminPreferencesParams struct {
	AdminAccountID      uuid.UUID
	Appearance          string
	Haptics             bool
	DefaultLandingRoute string
}

// The profile screen's preferences. Only these columns; notification columns keep their
// stored values (or their declared defaults on first write).
func (q *Queries) UpsertAdminPreferences(ctx context.Context, arg UpsertAdminPreferencesParams) error {
	_, err := q.db.Exec(ctx, upsertAdminPreferences,
		arg.AdminAccountID,
		arg.Appearance,
		arg.Haptics,
		arg.DefaultLandingRoute,
	)
	return err
}
