// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alert.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kokkondaBhanuteja/sethu-care/internal/money"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts
SET acknowledged_by = $1, acknowledged_at = now()
WHERE id = $2 AND acknowledged_at IS NULL
RETURNING id, acknowledged_at
`

type AcknowledgeAlertParams struct {
	AdminID *uuid.UUID
	ID      uuid.UUID
}

type AcknowledgeAlertRow struct {
	ID             uuid.UUID
	AcknowledgedAt pgtype.Timestamptz
}

// First writer wins: the WHERE arm makes two racing admins resolve in the database, and a
// zero-row result tells the service somebody else already owns it (or the id is unknown).
func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (AcknowledgeAlertRow, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, arg.AdminID, arg.ID)
	var i AcknowledgeAlertRow
	err := row.Scan(&i.ID, &i.AcknowledgedAt)
	return i, err
}

const countAlerts = `-- name: CountAlerts :one
SELECT count(*)::int AS total
FROM alerts al
WHERE ($1::text IS NULL OR al.severity = $1::text)
  AND ($2::boolean IS NULL
       OR (al.acknowledged_at IS NOT NULL) = $2::boolean)
`

type CountAlertsParams struct {
	SeverityFilter     *string
	AcknowledgedFilter *bool
}

// Whole-set total for the same filter as ListAlerts (minus the cursor).
func (q *Queries) CountAlerts(ctx context.Context, arg CountAlertsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countAlerts, arg.SeverityFilter, arg.AcknowledgedFilter)
	var total int32
	err := row.Scan(&total)
	return total, err
}

const countOpenCriticalAlerts = `-- name: CountOpenCriticalAlerts :one
SELECT count(*)::int AS open_critical
FROM alerts
WHERE requires_acknowledgement AND acknowledged_at IS NULL
`

// Unacknowledged criticals — the shell badge and the dashboard band's number.
func (q *Queries) CountOpenCriticalAlerts(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countOpenCriticalAlerts)
	var open_critical int32
	err := row.Scan(&open_critical)
	return open_critical, err
}

const getAlert = `-- name: GetAlert :one
SELECT
  al.id, al.kind, al.severity, al.subject_kind, al.subject_id,
  al.requires_acknowledgement, al.acknowledged_by, al.acknowledged_at, al.created_at,
  acknowledger.name AS acknowledger_name,
  s.name  AS service_name,
  addr.city,
  customer.name AS customer_name,
  b.state AS booking_state,
  -- COALESCEd so a subjectless alert still scans; booking_state IS NULL says whether the
  -- amount is real or the placeholder zero.
  COALESCE(b.quoted_total_paise, 0) AS booking_total_paise,
  b.created_at AS booking_created_at
FROM alerts al
LEFT JOIN users acknowledger  ON acknowledger.id = al.acknowledged_by
LEFT JOIN bookings b          ON al.subject_kind = 'BOOKING' AND b.id = al.subject_id
LEFT JOIN users customer      ON customer.id = b.customer_id
LEFT JOIN booking_items bi    ON bi.booking_id = b.id
LEFT JOIN services s          ON s.id = bi.service_id
LEFT JOIN addresses addr      ON addr.id = b.address_id
WHERE al.id = $1
`

type GetAlertRow struct {
	ID                      uuid.UUID
	Kind                    string
	Severity                string
	SubjectKind             *string
	SubjectID               *uuid.UUID
	RequiresAcknowledgement bool
	AcknowledgedBy          *uuid.UUID
	AcknowledgedAt          pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	AcknowledgerName        *string
	ServiceName             *string
	City                    *string
	CustomerName            *string
	BookingState            *string
	BookingTotalPaise       money.Money
	BookingCreatedAt        pgtype.Timestamptz
}

// One alert by its OWN id, with the same read-time context as the list.
func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (GetAlertRow, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i GetAlertRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Severity,
		&i.SubjectKind,
		&i.SubjectID,
		&i.RequiresAcknowledgement,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.CreatedAt,
		&i.AcknowledgerName,
		&i.ServiceName,
		&i.City,
		&i.CustomerName,
		&i.BookingState,
		&i.BookingTotalPaise,
		&i.BookingCreatedAt,
	)
	return i, err
}

const getAlertEscalationContext = `-- name: GetAlertEscalationContext :one
SELECT be.from_state, be.created_at
FROM booking_events be
WHERE be.booking_id = $1 AND be.to_state = 'ESCALATED'
ORDER BY be.created_at DESC
LIMIT 1
`

type GetAlertEscalationContextRow struct {
	FromState string
	CreatedAt pgtype.Timestamptz
}

// The why-it-fired facts for a BOOKING_ESCALATED alert: the escalation transition itself.
func (q *Queries) GetAlertEscalationContext(ctx context.Context, bookingID uuid.UUID) (GetAlertEscalationContextRow, error) {
	row := q.db.QueryRow(ctx, getAlertEscalationContext, bookingID)
	var i GetAlertEscalationContextRow
	err := row.Scan(&i.FromState, &i.CreatedAt)
	return i, err
}

const getAlertNoteByKey = `-- name: GetAlertNoteByKey :one
SELECT an.id, an.body, an.created_at, author.name AS author_name
FROM alert_notes an
JOIN users author ON author.id = an.author_user_id
WHERE an.alert_id = $1
  AND an.author_user_id = $2
  AND an.idempotency_key = $3
`

type GetAlertNoteByKeyParams struct {
	AlertID        uuid.UUID
	AuthorUserID   uuid.UUID
	IdempotencyKey string
}

type GetAlertNoteByKeyRow struct {
	ID         uuid.UUID
	Body       string
	CreatedAt  pgtype.Timestamptz
	AuthorName string
}

func (q *Queries) GetAlertNoteByKey(ctx context.Context, arg GetAlertNoteByKeyParams) (GetAlertNoteByKeyRow, error) {
	row := q.db.QueryRow(ctx, getAlertNoteByKey, arg.AlertID, arg.AuthorUserID, arg.IdempotencyKey)
	var i GetAlertNoteByKeyRow
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CreatedAt,
		&i.AuthorName,
	)
	return i, err
}

const getNewestAlertIDBySubject = `-- name: GetNewestAlertIDBySubject :one
SELECT id FROM alerts
WHERE subject_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The phase-1 id convention: the attention queue advertised alertId = booking id before the
// alerts table existed, so a subject id resolves to that subject's newest alert.
func (q *Queries) GetNewestAlertIDBySubject(ctx context.Context, subjectID *uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getNewestAlertIDBySubject, subjectID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertAlertNote = `-- name: InsertAlertNote :exec
INSERT INTO alert_notes (alert_id, author_user_id, idempotency_key, body)
VALUES ($1, $2, $3, $4)
ON CONFLICT (alert_id, author_user_id, idempotency_key) DO NOTHING
`

type InsertAlertNoteParams struct {
	AlertID        uuid.UUID
	AuthorUserID   uuid.UUID
	IdempotencyKey string
	Body           string
}

// Replay-safe note write: a retried Idempotency-Key lands on the unique index and no-ops;
// GetAlertNoteByKey then returns the first attempt's row either way.
func (q *Queries) InsertAlertNote(ctx context.Context, arg InsertAlertNoteParams) error {
	_, err := q.db.Exec(ctx, insertAlertNote,
		arg.AlertID,
		arg.AuthorUserID,
		arg.IdempotencyKey,
		arg.Body,
	)
	return err
}

const insertSubjectAlert = `-- name: InsertSubjectAlert :execrows
INSERT INTO alerts (kind, severity, subject_kind, subject_id, source_event_id, requires_acknowledgement)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT DO NOTHING
`

type InsertSubjectAlertParams struct {
	Kind                    string
	Severity                string
	SubjectKind             *string
	SubjectID               *uuid.UUID
	SourceEventID           *uuid.UUID
	RequiresAcknowledgement bool
}

// The alert engine's one write: an alert about a subject, born from an outbox event.
// ON CONFLICT DO NOTHING covers BOTH idempotency guards — the redelivered event
// (source_event_id UNIQUE) and the already-open alert for the same (kind, subject).
func (q *Queries) InsertSubjectAlert(ctx context.Context, arg InsertSubjectAlertParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertSubjectAlert,
		arg.Kind,
		arg.Severity,
		arg.SubjectKind,
		arg.SubjectID,
		arg.SourceEventID,
		arg.RequiresAcknowledgement,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAlertNotes = `-- name: ListAlertNotes :many
SELECT an.id, an.body, an.created_at, author.name AS author_name
FROM alert_notes an
JOIN users author ON author.id = an.author_user_id
WHERE an.alert_id = $1
ORDER BY an.created_at, an.id
`

type ListAlertNotesRow struct {
	ID         uuid.UUID
	Body       string
	CreatedAt  pgtype.Timestamptz
	AuthorName string
}

func (q *Queries) ListAlertNotes(ctx context.Context, alertID uuid.UUID) ([]ListAlertNotesRow, error) {
	rows, err := q.db.Query(ctx, listAlertNotes, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertNotesRow{}
	for rows.Next() {
		var i ListAlertNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertSubjectHistory = `-- name: ListAlertSubjectHistory :many
SELECT be.id, be.action, be.from_state, be.to_state, be.created_at
FROM booking_events be
WHERE be.booking_id = $1
ORDER BY be.created_at, be.id
`

type ListAlertSubjectHistoryRow struct {
	ID        uuid.UUID
	Action    string
	FromState string
	ToState   string
	CreatedAt pgtype.Timestamptz
}

// The dispatch history behind a booking-subject alert: the booking's own transition log,
// read-only. The service renders each row as state codes, never composed prose.
func (q *Queries) ListAlertSubjectHistory(ctx context.Context, bookingID uuid.UUID) ([]ListAlertSubjectHistoryRow, error) {
	rows, err := q.db.Query(ctx, listAlertSubjectHistory, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertSubjectHistoryRow{}
	for rows.Next() {
		var i ListAlertSubjectHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.FromState,
			&i.ToState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT
  al.id, al.kind, al.severity, al.subject_kind, al.subject_id,
  al.requires_acknowledgement, al.acknowledged_by, al.acknowledged_at, al.created_at,
  acknowledger.name AS acknowledger_name,
  s.name  AS service_name,
  addr.city
FROM alerts al
LEFT JOIN users acknowledger  ON acknowledger.id = al.acknowledged_by
LEFT JOIN bookings b          ON al.subject_kind = 'BOOKING' AND b.id = al.subject_id
LEFT JOIN booking_items bi    ON bi.booking_id = b.id
LEFT JOIN services s          ON s.id = bi.service_id
LEFT JOIN addresses addr      ON addr.id = b.address_id
WHERE ($1::text IS NULL OR al.severity = $1::text)
  AND ($2::boolean IS NULL
       OR (al.acknowledged_at IS NOT NULL) = $2::boolean)
  AND ($3::timestamptz IS NULL
       OR al.created_at < $3::timestamptz
       OR (al.created_at = $3::timestamptz
           AND al.id < $4::uuid))
ORDER BY al.created_at DESC, al.id DESC
LIMIT $5::int
`

type ListAlertsParams struct {
	SeverityFilter     *string
	AcknowledgedFilter *bool
	CursorCreatedAt    pgtype.Timestamptz
	CursorID           *uuid.UUID
	RowLimit           int32
}

type ListAlertsRow struct {
	ID                      uuid.UUID
	Kind                    string
	Severity                string
	SubjectKind             *string
	SubjectID               *uuid.UUID
	RequiresAcknowledgement bool
	AcknowledgedBy          *uuid.UUID
	AcknowledgedAt          pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	AcknowledgerName        *string
	ServiceName             *string
	City                    *string
}

// The alert feed, newest first, keyset-paginated. Booking context (service, city) is joined
// read-only so the title/summary interpolation values are derived at read time — the alert
// row stores facts, not display strings. Rows whose subject booking has vanished still list
// (LEFT JOINs): an alert must never disappear because its subject did.
func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts,
		arg.SeverityFilter,
		arg.AcknowledgedFilter,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsRow{}
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Severity,
			&i.SubjectKind,
			&i.SubjectID,
			&i.RequiresAcknowledgement,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.CreatedAt,
			&i.AcknowledgerName,
			&i.ServiceName,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsBySubject = `-- name: ListAlertsBySubject :many
SELECT al.id, al.kind, al.severity, al.created_at
FROM alerts al
WHERE al.subject_id = $1 AND al.id <> $2
ORDER BY al.created_at DESC, al.id DESC
`

type ListAlertsBySubjectParams struct {
	SubjectID   *uuid.UUID
	ExcludingID uuid.UUID
}

type ListAlertsBySubjectRow struct {
	ID        uuid.UUID
	Kind      string
	Severity  string
	CreatedAt pgtype.Timestamptz
}

// The other alerts about the same subject, for the detail's related-alerts rail.
func (q *Queries) ListAlertsBySubject(ctx context.Context, arg ListAlertsBySubjectParams) ([]ListAlertsBySubjectRow, error) {
	rows, err := q.db.Query(ctx, listAlertsBySubject, arg.SubjectID, arg.ExcludingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsBySubjectRow{}
	for rows.Next() {
		var i ListAlertsBySubjectRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Severity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCriticalAlertExamples = `-- name: ListOpenCriticalAlertExamples :many
SELECT al.id, al.kind, al.subject_kind, al.subject_id, al.created_at
FROM alerts al
WHERE al.requires_acknowledgement AND al.acknowledged_at IS NULL
ORDER BY al.created_at DESC, al.id DESC
LIMIT $1::int
`

type ListOpenCriticalAlertExamplesRow struct {
	ID          uuid.UUID
	Kind        string
	SubjectKind *string
	SubjectID   *uuid.UUID
	CreatedAt   pgtype.Timestamptz
}

// The band's example refs: the newest unacknowledged criticals, at most @row_limit.
func (q *Queries) ListOpenCriticalAlertExamples(ctx context.Context, rowLimit int32) ([]ListOpenCriticalAlertExamplesRow, error) {
	rows, err := q.db.Query(ctx, listOpenCriticalAlertExamples, rowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenCriticalAlertExamplesRow{}
	for rows.Next() {
		var i ListOpenCriticalAlertExamplesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.SubjectKind,
			&i.SubjectID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInformationalAlertsRead = `-- name: MarkInformationalAlertsRead :execrows
UPDATE alerts
SET read_at = now()
WHERE requires_acknowledgement = false AND read_at IS NULL
`

// The read-all sweep. The requires_acknowledgement guard is the badge-discipline rule: a
// critical alert can only leave the needs-action tier through acknowledgeAlert.
func (q *Queries) MarkInformationalAlertsRead(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, markInformationalAlertsRead)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
