// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_user_id, actor_kind, action, entity_type, entity_id, before, after, correlation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	ActorUserID   *uuid.UUID
	ActorKind     string
	Action        string
	EntityType    string
	EntityID      uuid.UUID
	Before        []byte
	After         []byte
	CorrelationID *uuid.UUID
}

// Write an audit row. Meant to run inside the caller's transaction (pass the same tx) so it commits
// atomically with the change it records.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.ActorKind,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.CorrelationID,
	)
	return err
}
