// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountAuditLogs = `-- name: AdminCountAuditLogs :one
SELECT
  count(*)::int AS total,
  min(al.created_at)::timestamptz AS range_from,
  max(al.created_at)::timestamptz AS range_to
FROM audit_logs al
JOIN users admin_user ON admin_user.id = al.actor_user_id
WHERE admin_user.role = 'ADMIN'
  AND al.entity_type = 'booking'
  AND al.action = ANY($1::text[])
  AND ($2::uuid IS NULL OR al.actor_user_id = $2::uuid)
  AND ($3::text IS NULL OR al.action = $3::text)
  AND ($4::uuid IS NULL OR al.entity_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR al.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR al.created_at < $6::timestamptz)
`

type AdminCountAuditLogsParams struct {
	Actions      []string
	AdminFilter  *uuid.UUID
	ActionFilter *string
	EntityFilter *uuid.UUID
	FromTime     pgtype.Timestamptz
	ToTime       pgtype.Timestamptz
}

type AdminCountAuditLogsRow struct {
	Total     int32
	RangeFrom pgtype.Timestamptz
	RangeTo   pgtype.Timestamptz
}

// Total and timestamp range for the same filter as AdminListAuditLogs (minus the cursor), so
// the console's "N entries · from – to" line covers the whole result set, not one page.
func (q *Queries) AdminCountAuditLogs(ctx context.Context, arg AdminCountAuditLogsParams) (AdminCountAuditLogsRow, error) {
	row := q.db.QueryRow(ctx, adminCountAuditLogs,
		arg.Actions,
		arg.AdminFilter,
		arg.ActionFilter,
		arg.EntityFilter,
		arg.FromTime,
		arg.ToTime,
	)
	var i AdminCountAuditLogsRow
	err := row.Scan(&i.Total, &i.RangeFrom, &i.RangeTo)
	return i, err
}

const adminGetAuditLog = `-- name: AdminGetAuditLog :one
SELECT
  al.id, al.action, al.entity_type, al.entity_id, al.before, al.after, al.created_at,
  admin_user.id   AS admin_id,
  admin_user.name AS admin_name
FROM audit_logs al
JOIN users admin_user ON admin_user.id = al.actor_user_id
WHERE al.id = $1
  AND admin_user.role = 'ADMIN'
  AND al.entity_type = 'booking'
  AND al.action = ANY($2::text[])
`

type AdminGetAuditLogParams struct {
	ID      uuid.UUID
	Actions []string
}

type AdminGetAuditLogRow struct {
	ID         uuid.UUID
	Action     string
	EntityType string
	EntityID   uuid.UUID
	Before     []byte
	After      []byte
	CreatedAt  pgtype.Timestamptz
	AdminID    uuid.UUID
	AdminName  string
}

// One audit entry by id, for the detail screen — under the SAME visibility rule as the list
// (admin actor, booking entity, actions the console vocabulary names), so a deep link can
// never show more than the list would.
func (q *Queries) AdminGetAuditLog(ctx context.Context, arg AdminGetAuditLogParams) (AdminGetAuditLogRow, error) {
	row := q.db.QueryRow(ctx, adminGetAuditLog, arg.ID, arg.Actions)
	var i AdminGetAuditLogRow
	err := row.Scan(
		&i.ID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Before,
		&i.After,
		&i.CreatedAt,
		&i.AdminID,
		&i.AdminName,
	)
	return i, err
}

const adminListAuditActors = `-- name: AdminListAuditActors :many
SELECT DISTINCT
  admin_user.id,
  admin_user.name
FROM audit_logs al
JOIN users admin_user ON admin_user.id = al.actor_user_id
WHERE admin_user.role = 'ADMIN'
  AND al.entity_type = 'booking'
  AND al.action = ANY($1::text[])
ORDER BY admin_user.name, admin_user.id
`

type AdminListAuditActorsRow struct {
	ID   uuid.UUID
	Name string
}

// The distinct admins present in the audit log, for the filter dropdown — derived here so the
// console never pages the whole ledger to build a filter. Same visibility rule as the list.
func (q *Queries) AdminListAuditActors(ctx context.Context, actions []string) ([]AdminListAuditActorsRow, error) {
	rows, err := q.db.Query(ctx, adminListAuditActors, actions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAuditActorsRow{}
	for rows.Next() {
		var i AdminListAuditActorsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListAuditLogs = `-- name: AdminListAuditLogs :many
SELECT
  al.id, al.action, al.entity_type, al.entity_id, al.before, al.after, al.created_at,
  admin_user.id   AS admin_id,
  admin_user.name AS admin_name
FROM audit_logs al
JOIN users admin_user ON admin_user.id = al.actor_user_id
WHERE admin_user.role = 'ADMIN'
  AND al.entity_type = 'booking'
  AND al.action = ANY($1::text[])
  AND ($2::uuid IS NULL OR al.actor_user_id = $2::uuid)
  AND ($3::text IS NULL OR al.action = $3::text)
  AND ($4::uuid IS NULL OR al.entity_id = $4::uuid)
  AND ($5::timestamptz IS NULL OR al.created_at >= $5::timestamptz)
  AND ($6::timestamptz IS NULL OR al.created_at < $6::timestamptz)
  AND ($7::timestamptz IS NULL
       OR al.created_at < $7::timestamptz
       OR (al.created_at = $7::timestamptz
           AND al.id < $8::uuid))
ORDER BY al.created_at DESC, al.id DESC
LIMIT $9::int
`

type AdminListAuditLogsParams struct {
	Actions         []string
	AdminFilter     *uuid.UUID
	ActionFilter    *string
	EntityFilter    *uuid.UUID
	FromTime        pgtype.Timestamptz
	ToTime          pgtype.Timestamptz
	CursorCreatedAt pgtype.Timestamptz
	CursorID        *uuid.UUID
	RowLimit        int32
}

type AdminListAuditLogsRow struct {
	ID         uuid.UUID
	Action     string
	EntityType string
	EntityID   uuid.UUID
	Before     []byte
	After      []byte
	CreatedAt  pgtype.Timestamptz
	AdminID    uuid.UUID
	AdminName  string
}

// The admin console's audit list: entries recorded against bookings by a human ADMIN actor,
// restricted to the actions the console's audit vocabulary can name (see internal/audit
// AdminActions). Keyset-paginated newest first. The users join is read-only display data —
// identity remains the owner of users.
func (q *Queries) AdminListAuditLogs(ctx context.Context, arg AdminListAuditLogsParams) ([]AdminListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, adminListAuditLogs,
		arg.Actions,
		arg.AdminFilter,
		arg.ActionFilter,
		arg.EntityFilter,
		arg.FromTime,
		arg.ToTime,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListAuditLogsRow{}
	for rows.Next() {
		var i AdminListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.AdminID,
			&i.AdminName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAdminAuditActionsSince = `-- name: CountAdminAuditActionsSince :one
SELECT count(*)::int AS total, min(created_at)::timestamptz AS oldest
FROM audit_logs
WHERE actor_user_id = $1
  AND action = $2
  AND entity_type = 'booking'
  AND created_at >= $3
`

type CountAdminAuditActionsSinceParams struct {
	ActorUserID *uuid.UUID
	Action      string
	CreatedAt   pgtype.Timestamptz
}

type CountAdminAuditActionsSinceRow struct {
	Total  int32
	Oldest pgtype.Timestamptz
}

// How often an admin has performed a booking action recently, plus the oldest occurrence in
// the window — the refund rate limit's counter and its reset instant. entity_type is pinned
// to 'booking' so the admin_action_key replay rows (which reuse the action name) never
// double-count.
func (q *Queries) CountAdminAuditActionsSince(ctx context.Context, arg CountAdminAuditActionsSinceParams) (CountAdminAuditActionsSinceRow, error) {
	row := q.db.QueryRow(ctx, countAdminAuditActionsSince, arg.ActorUserID, arg.Action, arg.CreatedAt)
	var i CountAdminAuditActionsSinceRow
	err := row.Scan(&i.Total, &i.Oldest)
	return i, err
}

const getAdminActionReplay = `-- name: GetAdminActionReplay :one
SELECT after
FROM audit_logs
WHERE entity_type = 'admin_action_key' AND entity_id = $1
ORDER BY created_at, id
LIMIT 1
`

// The idempotent-replay record for an admin mutation: the receipt stored under the derived
// key id (entity_type 'admin_action_key'). Oldest first — the FIRST result is the one a
// replayed Idempotency-Key must return.
func (q *Queries) GetAdminActionReplay(ctx context.Context, entityID uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getAdminActionReplay, entityID)
	var after []byte
	err := row.Scan(&after)
	return after, err
}

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (actor_user_id, actor_kind, action, entity_type, entity_id, before, after, correlation_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertAuditLogParams struct {
	ActorUserID   *uuid.UUID
	ActorKind     string
	Action        string
	EntityType    string
	EntityID      uuid.UUID
	Before        []byte
	After         []byte
	CorrelationID *uuid.UUID
}

// Write an audit row. Meant to run inside the caller's transaction (pass the same tx) so it commits
// atomically with the change it records.
func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.ActorKind,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Before,
		arg.After,
		arg.CorrelationID,
	)
	return err
}
