// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gateway_events.sql

package sqlcgen

import (
	"context"
)

const getGatewayEventStatus = `-- name: GetGatewayEventStatus :one
SELECT status FROM payment_gateway_events WHERE gateway_event_id = $1
`

// The dedupe read: has this exact delivery already been applied?
func (q *Queries) GetGatewayEventStatus(ctx context.Context, gatewayEventID string) (string, error) {
	row := q.db.QueryRow(ctx, getGatewayEventStatus, gatewayEventID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const insertGatewayEvent = `-- name: InsertGatewayEvent :exec
INSERT INTO payment_gateway_events (provider, event_type, gateway_event_id, reference, provider_ref, payload)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (gateway_event_id) DO NOTHING
`

type InsertGatewayEventParams struct {
	Provider       string
	EventType      string
	GatewayEventID string
	Reference      string
	ProviderRef    string
	Payload        []byte
}

// Idempotent inbox write: a re-delivery of the same gateway_event_id is a no-op.
func (q *Queries) InsertGatewayEvent(ctx context.Context, arg InsertGatewayEventParams) error {
	_, err := q.db.Exec(ctx, insertGatewayEvent,
		arg.Provider,
		arg.EventType,
		arg.GatewayEventID,
		arg.Reference,
		arg.ProviderRef,
		arg.Payload,
	)
	return err
}

const listParkedGatewayEvents = `-- name: ListParkedGatewayEvents :many
SELECT gateway_event_id, event_type, reference, provider_ref, payload
  FROM payment_gateway_events
 WHERE status = 'RECEIVED'
   AND created_at <= now() - make_interval(mins => $1::int)
 ORDER BY created_at
 LIMIT $2
`

type ListParkedGatewayEventsParams struct {
	OlderThanMinutes int32
	MaxRows          int32
}

type ListParkedGatewayEventsRow struct {
	GatewayEventID string
	EventType      string
	Reference      string
	ProviderRef    string
	Payload        []byte
}

// Events accepted but not yet applied (the webhook beat the payment row). Fed to the replay sweep.
func (q *Queries) ListParkedGatewayEvents(ctx context.Context, arg ListParkedGatewayEventsParams) ([]ListParkedGatewayEventsRow, error) {
	rows, err := q.db.Query(ctx, listParkedGatewayEvents, arg.OlderThanMinutes, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListParkedGatewayEventsRow{}
	for rows.Next() {
		var i ListParkedGatewayEventsRow
		if err := rows.Scan(
			&i.GatewayEventID,
			&i.EventType,
			&i.Reference,
			&i.ProviderRef,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGatewayEventProcessed = `-- name: MarkGatewayEventProcessed :exec
UPDATE payment_gateway_events
   SET status = 'PROCESSED', processed_at = now()
 WHERE gateway_event_id = $1
`

func (q *Queries) MarkGatewayEventProcessed(ctx context.Context, gatewayEventID string) error {
	_, err := q.db.Exec(ctx, markGatewayEventProcessed, gatewayEventID)
	return err
}
