// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kokkondaBhanuteja/sethu-care/internal/money"
)

const adminCreditTotalsForOrder = `-- name: AdminCreditTotalsForOrder :one
SELECT
  COALESCE(SUM(amount_paise) FILTER (WHERE kind = 'CREDIT_ISSUED'), 0)::bigint   AS issued_paise,
  COALESCE(SUM(amount_paise) FILTER (WHERE kind = 'CREDIT_REDEEMED'), 0)::bigint AS redeemed_paise
FROM ledger_entries
WHERE order_id = $1
`

type AdminCreditTotalsForOrderRow struct {
	IssuedPaise   int64
	RedeemedPaise int64
}

// What has already been credited (and taken back) against an order — the refund screen's
// alreadyRefunded figure, over the whole credit history.
func (q *Queries) AdminCreditTotalsForOrder(ctx context.Context, orderID *uuid.UUID) (AdminCreditTotalsForOrderRow, error) {
	row := q.db.QueryRow(ctx, adminCreditTotalsForOrder, orderID)
	var i AdminCreditTotalsForOrderRow
	err := row.Scan(&i.IssuedPaise, &i.RedeemedPaise)
	return i, err
}

const adminLatestUnreversedCreditForOrder = `-- name: AdminLatestUnreversedCreditForOrder :one
SELECT credit.id, credit.amount_paise, credit.customer_id
FROM ledger_entries credit
WHERE credit.order_id = $1
  AND credit.kind = 'CREDIT_ISSUED'
  AND NOT EXISTS (
    SELECT 1 FROM ledger_entries reversal WHERE reversal.reverses_entry_id = credit.id
  )
ORDER BY credit.created_at DESC, credit.id DESC
LIMIT 1
`

type AdminLatestUnreversedCreditForOrderRow struct {
	ID          uuid.UUID
	AmountPaise money.Money
	CustomerID  *uuid.UUID
}

// The credit an undo-cancel must offset: the newest CREDIT_ISSUED on the order that no
// reversal row points at yet.
func (q *Queries) AdminLatestUnreversedCreditForOrder(ctx context.Context, orderID *uuid.UUID) (AdminLatestUnreversedCreditForOrderRow, error) {
	row := q.db.QueryRow(ctx, adminLatestUnreversedCreditForOrder, orderID)
	var i AdminLatestUnreversedCreditForOrderRow
	err := row.Scan(&i.ID, &i.AmountPaise, &i.CustomerID)
	return i, err
}

const completionLedgerExists = `-- name: CompletionLedgerExists :one
SELECT EXISTS (
  SELECT 1 FROM ledger_entries
   WHERE (order_id = $1 AND kind = 'REVENUE')
      OR (booking_id = $2 AND kind = 'CASH_CUSTODY')
) AS exists
`

type CompletionLedgerExistsParams struct {
	OrderID   *uuid.UUID
	BookingID *uuid.UUID
}

// Idempotency guard for the booking.completed consumer: has this booking already been billed?
// REVENUE attaches to the order; CASH_CUSTODY to the booking. In P1 an order has one booking,
// so either presence means "already recorded".
func (q *Queries) CompletionLedgerExists(ctx context.Context, arg CompletionLedgerExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, completionLedgerExists, arg.OrderID, arg.BookingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const creditExistsForOrder = `-- name: CreditExistsForOrder :one
SELECT EXISTS (
  SELECT 1 FROM ledger_entries WHERE order_id = $1 AND kind = 'CREDIT_ISSUED'
) AS exists
`

// Idempotency guard for the failed-booking credit consumer.
func (q *Queries) CreditExistsForOrder(ctx context.Context, orderID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, creditExistsForOrder, orderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const depositExistsForBooking = `-- name: DepositExistsForBooking :one
SELECT EXISTS (
  SELECT 1 FROM ledger_entries WHERE booking_id = $1 AND kind = 'CASH_DEPOSIT'
) AS exists
`

func (q *Queries) DepositExistsForBooking(ctx context.Context, bookingID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, depositExistsForBooking, bookingID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getBookingCashCustody = `-- name: GetBookingCashCustody :one
SELECT amount_paise, technician_id, created_at
  FROM ledger_entries
 WHERE booking_id = $1 AND kind = 'CASH_CUSTODY'
 LIMIT 1
`

type GetBookingCashCustodyRow struct {
	AmountPaise  money.Money
	TechnicianID *uuid.UUID
	CreatedAt    pgtype.Timestamptz
}

// The cash a technician is holding for a booking (the CASH_CUSTODY row), so a deposit can
// match its amount and be attributed to the right technician.
func (q *Queries) GetBookingCashCustody(ctx context.Context, bookingID *uuid.UUID) (GetBookingCashCustodyRow, error) {
	row := q.db.QueryRow(ctx, getBookingCashCustody, bookingID)
	var i GetBookingCashCustodyRow
	err := row.Scan(&i.AmountPaise, &i.TechnicianID, &i.CreatedAt)
	return i, err
}

const getRevenueEntryForOrder = `-- name: GetRevenueEntryForOrder :one
SELECT amount_paise, method, created_at
FROM ledger_entries
WHERE order_id = $1 AND kind = 'REVENUE'
ORDER BY created_at
LIMIT 1
`

type GetRevenueEntryForOrderRow struct {
	AmountPaise money.Money
	Method      *string
	CreatedAt   pgtype.Timestamptz
}

// The REVENUE row for an order — the money-moved record behind the console's payment panel.
// In P1 an order has exactly one booking, so one REVENUE row is the whole story.
func (q *Queries) GetRevenueEntryForOrder(ctx context.Context, orderID *uuid.UUID) (GetRevenueEntryForOrderRow, error) {
	row := q.db.QueryRow(ctx, getRevenueEntryForOrder, orderID)
	var i GetRevenueEntryForOrderRow
	err := row.Scan(&i.AmountPaise, &i.Method, &i.CreatedAt)
	return i, err
}

const getTechnicianCashPosition = `-- name: GetTechnicianCashPosition :one
SELECT
  position.collected_paise, position.deposited_paise, position.outstanding_paise
FROM technician_cash_position position
WHERE position.technician_id = $1
`

type GetTechnicianCashPositionRow struct {
	CollectedPaise   money.Money
	DepositedPaise   money.Money
	OutstandingPaise money.Money
}

// One technician's own cash standing, for the provider app's cash-held summary. Returns no row
// when they have never collected cash — the caller reads that as an all-zero position.
func (q *Queries) GetTechnicianCashPosition(ctx context.Context, technicianID *uuid.UUID) (GetTechnicianCashPositionRow, error) {
	row := q.db.QueryRow(ctx, getTechnicianCashPosition, technicianID)
	var i GetTechnicianCashPositionRow
	err := row.Scan(&i.CollectedPaise, &i.DepositedPaise, &i.OutstandingPaise)
	return i, err
}

const insertAdminCredit = `-- name: InsertAdminCredit :one

INSERT INTO ledger_entries (id, kind, amount_paise, order_id, customer_id, memo)
VALUES ($1, 'CREDIT_ISSUED', $2, $3, $4, $5)
RETURNING created_at
`

type InsertAdminCreditParams struct {
	ID          uuid.UUID
	AmountPaise money.Money
	OrderID     *uuid.UUID
	CustomerID  *uuid.UUID
	Memo        string
}

// ---------------------------------------------------------------------------
// Admin refunds (internal/ledger, driven by the rescue console).
// An admin-decided refund/goodwill credit. CREDIT_ISSUED attaches to the ORDER (the CHECK
// requires it). The id is minted by the CALLER so the refund receipt — stored in the same
// transaction as its idempotent-replay record — can name the credit before it exists.
func (q *Queries) InsertAdminCredit(ctx context.Context, arg InsertAdminCreditParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, insertAdminCredit,
		arg.ID,
		arg.AmountPaise,
		arg.OrderID,
		arg.CustomerID,
		arg.Memo,
	)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const insertCreditReversal = `-- name: InsertCreditReversal :one
INSERT INTO ledger_entries (kind, amount_paise, order_id, customer_id, memo, reverses_entry_id)
VALUES ('CREDIT_REDEEMED', $1, $2, $3, $4, $5)
RETURNING id
`

type InsertCreditReversalParams struct {
	AmountPaise     money.Money
	OrderID         *uuid.UUID
	CustomerID      *uuid.UUID
	Memo            string
	ReversesEntryID *uuid.UUID
}

// The offsetting row an undo writes: a CREDIT_REDEEMED pointing at the credit it takes
// back. The ledger is append-only — this is how a refund is "reversed".
func (q *Queries) InsertCreditReversal(ctx context.Context, arg InsertCreditReversalParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertCreditReversal,
		arg.AmountPaise,
		arg.OrderID,
		arg.CustomerID,
		arg.Memo,
		arg.ReversesEntryID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO ledger_entries (kind, amount_paise, order_id, booking_id, customer_id, technician_id, method, memo)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLedgerEntryParams struct {
	Kind         string
	AmountPaise  money.Money
	OrderID      *uuid.UUID
	BookingID    *uuid.UUID
	CustomerID   *uuid.UUID
	TechnicianID *uuid.UUID
	Method       *string
	Memo         string
}

// One append-only row. The database CHECK enforces the attach rules (REVENUE -> order,
// CASH_CUSTODY -> booking + technician + method=CASH), so a malformed entry is rejected here,
// not discovered later.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.Kind,
		arg.AmountPaise,
		arg.OrderID,
		arg.BookingID,
		arg.CustomerID,
		arg.TechnicianID,
		arg.Method,
		arg.Memo,
	)
	return err
}

const listCashReconciliation = `-- name: ListCashReconciliation :many
SELECT
  position.technician_id, u.name,
  position.collected_paise, position.deposited_paise, position.outstanding_paise,
  position.oldest_collection_at::timestamptz AS oldest_collection_at
FROM technician_cash_position position
JOIN users u ON u.id = position.technician_id
WHERE position.outstanding_paise > 0
ORDER BY position.oldest_collection_at
`

type ListCashReconciliationRow struct {
	TechnicianID       *uuid.UUID
	Name               string
	CollectedPaise     money.Money
	DepositedPaise     money.Money
	OutstandingPaise   money.Money
	OldestCollectionAt pgtype.Timestamptz
}

// The admin reconciliation view: every technician who still owes a deposit, oldest first.
func (q *Queries) ListCashReconciliation(ctx context.Context) ([]ListCashReconciliationRow, error) {
	rows, err := q.db.Query(ctx, listCashReconciliation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCashReconciliationRow{}
	for rows.Next() {
		var i ListCashReconciliationRow
		if err := rows.Scan(
			&i.TechnicianID,
			&i.Name,
			&i.CollectedPaise,
			&i.DepositedPaise,
			&i.OutstandingPaise,
			&i.OldestCollectionAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
