// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: map.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const mapActiveJobs = `-- name: MapActiveJobs :many
SELECT
  b.id,
  b.state,
  ST_Y(a.geog::geometry)::float8 AS lat,
  ST_X(a.geog::geometry)::float8 AS lng,
  s.name AS service_name
FROM bookings b
JOIN addresses a      ON a.id = b.address_id
JOIN booking_items bi ON bi.booking_id = b.id
JOIN services s       ON s.id = bi.service_id
WHERE b.state IN ('EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'ESCALATED')
ORDER BY b.created_at, b.id
`

type MapActiveJobsRow struct {
	ID          uuid.UUID
	State       string
	Lat         float64
	Lng         float64
	ServiceName string
}

// Job pins: bookings a technician is travelling to or working (plus escalations, which the
// map marks in their own colour). The pin sits on the booking's ADDRESS — the one position
// the platform always knows.
func (q *Queries) MapActiveJobs(ctx context.Context) ([]MapActiveJobsRow, error) {
	rows, err := q.db.Query(ctx, mapActiveJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapActiveJobsRow{}
	for rows.Next() {
		var i MapActiveJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.Lat,
			&i.Lng,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapAttentionItems = `-- name: MapAttentionItems :many
SELECT
  b.id,
  b.state,
  COALESCE(
    (SELECT max(be.created_at) FROM booking_events be
      WHERE be.booking_id = b.id AND be.to_state = b.state),
    b.created_at
  )::timestamptz AS waiting_since
FROM bookings b
WHERE b.state IN ('SEARCHING', 'ESCALATED')
ORDER BY waiting_since, b.id
`

type MapAttentionItemsRow struct {
	ID           uuid.UUID
	State        string
	WaitingSince pgtype.Timestamptz
}

// The map's attention rail: the same SEARCHING/ESCALATED membership as the dashboard queue,
// with when the problem surfaced (entry into the current state).
func (q *Queries) MapAttentionItems(ctx context.Context) ([]MapAttentionItemsRow, error) {
	rows, err := q.db.Query(ctx, mapAttentionItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapAttentionItemsRow{}
	for rows.Next() {
		var i MapAttentionItemsRow
		if err := rows.Scan(&i.ID, &i.State, &i.WaitingSince); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mapCityTotals = `-- name: MapCityTotals :one
SELECT
  (SELECT count(*) FROM bookings
    WHERE state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION'))::int AS active_jobs,
  (SELECT count(*) FROM technicians WHERE is_online AND NOT on_leave)::int AS online_providers
`

type MapCityTotalsRow struct {
	ActiveJobs      int32
	OnlineProviders int32
}

// The city-wide counters the snapshot carries alongside its markers: totals, not a count of
// the markers in the response.
func (q *Queries) MapCityTotals(ctx context.Context) (MapCityTotalsRow, error) {
	row := q.db.QueryRow(ctx, mapCityTotals)
	var i MapCityTotalsRow
	err := row.Scan(&i.ActiveJobs, &i.OnlineProviders)
	return i, err
}

const mapTechnicianPositions = `-- name: MapTechnicianPositions :many

SELECT
  t.user_id,
  u.name,
  t.last_lat::float8      AS lat,
  t.last_lng::float8      AS lng,
  t.last_location_at,
  t.is_online,
  -- COALESCEd to the nil uuid so the row scans without a pointer; uuid.Nil means "free".
  COALESCE(active.booking_id, '00000000-0000-0000-0000-000000000000'::uuid) AS active_booking_id
FROM technicians t
JOIN users u ON u.id = t.user_id
LEFT JOIN LATERAL (
  SELECT b.id AS booking_id
  FROM bookings b
  WHERE b.technician_id = t.user_id
    AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION')
  ORDER BY b.updated_at DESC
  LIMIT 1
) active ON true
WHERE t.last_lat IS NOT NULL
  AND t.last_lng IS NOT NULL
  AND t.last_location_at >= $1::timestamptz
ORDER BY t.last_location_at DESC, t.user_id
`

type MapTechnicianPositionsRow struct {
	UserID          uuid.UUID
	Name            string
	Lat             float64
	Lng             float64
	LastLocationAt  pgtype.Timestamptz
	IsOnline        bool
	ActiveBookingID uuid.UUID
}

// The live operations map (opsLiveMap). All reads; ops owns no aggregate. Positions come from
// the technician last-known-location columns (migration 00014); job pins from bookings joined
// to their address geography. There is NO zones table yet — the snapshot's zones are honestly
// empty and every zoneId is the empty string (see internal/ops/livemap.go).
// Technicians with a position inside the freshness window. An older position is filtered out
// entirely — a pin the platform cannot vouch for is worse than no pin. The lateral join finds
// the booking the technician is actively working, which is what turns the marker busy.
func (q *Queries) MapTechnicianPositions(ctx context.Context, freshAfter pgtype.Timestamptz) ([]MapTechnicianPositionsRow, error) {
	rows, err := q.db.Query(ctx, mapTechnicianPositions, freshAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MapTechnicianPositionsRow{}
	for rows.Next() {
		var i MapTechnicianPositionsRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.LastLocationAt,
			&i.IsOnline,
			&i.ActiveBookingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
