// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kokkondaBhanuteja/sethu-care/internal/money"
)

type Address struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Label     string
	Line1     string
	Line2     string
	City      string
	Pincode   string
	Geog      interface{}
	IsDefault bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type Alert struct {
	ID                      uuid.UUID
	Kind                    string
	Severity                string
	SubjectKind             *string
	SubjectID               *uuid.UUID
	SourceEventID           *uuid.UUID
	RequiresAcknowledgement bool
	AcknowledgedBy          *uuid.UUID
	AcknowledgedAt          pgtype.Timestamptz
	ReadAt                  pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
}

type AlertNote struct {
	ID             uuid.UUID
	AlertID        uuid.UUID
	AuthorUserID   uuid.UUID
	IdempotencyKey string
	Body           string
	CreatedAt      pgtype.Timestamptz
}

type AuditLog struct {
	ID            uuid.UUID
	ActorUserID   *uuid.UUID
	ActorKind     string
	Action        string
	EntityType    string
	EntityID      uuid.UUID
	Before        []byte
	After         []byte
	CorrelationID *uuid.UUID
	IpAddress     *string
	UserAgent     *string
	Metadata      []byte
	CreatedAt     pgtype.Timestamptz
}

type Booking struct {
	ID               uuid.UUID
	OrderID          uuid.UUID
	CustomerID       uuid.UUID
	AddressID        uuid.UUID
	TechnicianID     *uuid.UUID
	ProductUnitID    *uuid.UUID
	State            string
	ScheduledFor     pgtype.Timestamptz
	QuotedTotalPaise money.Money
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int64
	DurationMinutes  int32
	ScheduledEnd     pgtype.Timestamptz
}

type BookingEvent struct {
	ID          uuid.UUID
	BookingID   uuid.UUID
	FromState   string
	Action      string
	ToState     string
	ActorUserID *uuid.UUID
	Meta        []byte
	CreatedAt   pgtype.Timestamptz
}

type BookingItem struct {
	ID             uuid.UUID
	BookingID      uuid.UUID
	ServiceID      uuid.UUID
	VariantID      uuid.UUID
	Quantity       int32
	LineTotalPaise money.Money
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int64
}

type Category struct {
	ID        uuid.UUID
	Name      string
	Slug      string
	SortOrder int32
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type LedgerEntry struct {
	ID              uuid.UUID
	Kind            string
	AmountPaise     money.Money
	OrderID         *uuid.UUID
	BookingID       *uuid.UUID
	CustomerID      *uuid.UUID
	TechnicianID    *uuid.UUID
	Method          *string
	Memo            string
	ReversesEntryID *uuid.UUID
	CreatedAt       pgtype.Timestamptz
}

type NotificationLog struct {
	ID          uuid.UUID
	RecipientID uuid.UUID
	Channel     string
	EventType   string
	BookingID   *uuid.UUID
	Body        string
	CreatedAt   pgtype.Timestamptz
}

type Order struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Status     string
	TotalPaise money.Money
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Version    int64
}

type OtpChallenge struct {
	ID          uuid.UUID
	Purpose     string
	BookingID   *uuid.UUID
	Phone       string
	CodeHash    string
	Attempts    int32
	MaxAttempts int32
	ConsumedAt  pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Version     int64
}

type Outbox struct {
	ID            uuid.UUID
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	PublishedAt   pgtype.Timestamptz
	Attempts      int32
	LastError     *string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Payment struct {
	ID             uuid.UUID
	BookingID      uuid.UUID
	OrderID        uuid.UUID
	AmountPaise    money.Money
	Reference      string
	Status         string
	ProviderRef    *string
	CreatedAt      pgtype.Timestamptz
	CapturedAt     pgtype.Timestamptz
	PaymentLinkUrl string
}

type PaymentGatewayEvent struct {
	ID             uuid.UUID
	Provider       string
	EventType      string
	GatewayEventID string
	Reference      string
	ProviderRef    string
	Payload        []byte
	Status         string
	ProcessedAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
}

type ProductModel struct {
	ID             uuid.UUID
	CategoryID     uuid.UUID
	Brand          string
	Model          string
	WarrantyMonths int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int64
}

type ProductUnit struct {
	ID                uuid.UUID
	ProductModelID    uuid.UUID
	SerialNumber      string
	OwnerUserID       *uuid.UUID
	SoldAt            pgtype.Timestamptz
	WarrantyExpiresAt pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	Version           int64
}

type QuestionDef struct {
	ID         uuid.UUID
	ServiceID  uuid.UUID
	Prompt     string
	Kind       string
	Options    []string
	IsRequired bool
	SortOrder  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	Version    int64
}

type Review struct {
	ID           uuid.UUID
	BookingID    uuid.UUID
	CustomerID   uuid.UUID
	TechnicianID uuid.UUID
	Rating       int32
	Comment      string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Version      int64
}

type Service struct {
	ID               uuid.UUID
	CategoryID       uuid.UUID
	Name             string
	Slug             string
	Description      string
	AssignmentMode   string
	EstimatedMinutes int32
	IsActive         bool
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Version          int64
}

type ServiceRequiredSkill struct {
	ServiceID uuid.UUID
	SkillID   uuid.UUID
}

type ServiceVariant struct {
	ID             uuid.UUID
	ServiceID      uuid.UUID
	Name           string
	BasePricePaise money.Money
	IsActive       bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Version        int64
}

type Skill struct {
	ID        uuid.UUID
	Code      string
	Name      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
}

type Technician struct {
	UserID              uuid.UUID
	Role                string
	City                string
	ShiftStartMinute    int32
	ShiftEndMinute      int32
	OnLeave             bool
	IsOnline            bool
	ServiceRadiusMetres int32
	MaxConcurrentJobs   int32
	AcceptanceRate      pgtype.Numeric
	Rating              pgtype.Numeric
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	Version             int64
	LastLat             *float64
	LastLng             *float64
	LastLocationAt      pgtype.Timestamptz
}

type TechnicianCashPosition struct {
	TechnicianID       *uuid.UUID
	CollectedPaise     money.Money
	DepositedPaise     money.Money
	OutstandingPaise   money.Money
	OldestCollectionAt interface{}
}

type TechnicianSkill struct {
	TechnicianID uuid.UUID
	SkillID      uuid.UUID
}

type User struct {
	ID        uuid.UUID
	Phone     string
	Name      string
	Role      string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Version   int64
	DeletedAt pgtype.Timestamptz
}

type WorkPhoto struct {
	ID         uuid.UUID
	BookingID  uuid.UUID
	UploadedBy uuid.UUID
	Kind       string
	Url        string
	CreatedAt  pgtype.Timestamptz
}
