// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/kokkondaBhanuteja/sethu-care/internal/money"
)

const adminApplicationCategories = `-- name: AdminApplicationCategories :many
SELECT name, years_claimed
FROM provider_application_categories
WHERE application_id = $1
ORDER BY name
`

type AdminApplicationCategoriesRow struct {
	Name         string
	YearsClaimed int32
}

func (q *Queries) AdminApplicationCategories(ctx context.Context, applicationID uuid.UUID) ([]AdminApplicationCategoriesRow, error) {
	rows, err := q.db.Query(ctx, adminApplicationCategories, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminApplicationCategoriesRow{}
	for rows.Next() {
		var i AdminApplicationCategoriesRow
		if err := rows.Scan(&i.Name, &i.YearsClaimed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminApplicationDocuments = `-- name: AdminApplicationDocuments :many
SELECT id, document_type, validation, uploaded_at, expires_at, detail,
       ocr_read, ocr_expected, size_bytes, url
FROM provider_application_documents
WHERE application_id = $1
ORDER BY created_at, document_type
`

type AdminApplicationDocumentsRow struct {
	ID           uuid.UUID
	DocumentType string
	Validation   string
	UploadedAt   pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	Detail       string
	OcrRead      string
	OcrExpected  string
	SizeBytes    int64
	Url          string
}

func (q *Queries) AdminApplicationDocuments(ctx context.Context, applicationID uuid.UUID) ([]AdminApplicationDocumentsRow, error) {
	rows, err := q.db.Query(ctx, adminApplicationDocuments, applicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminApplicationDocumentsRow{}
	for rows.Next() {
		var i AdminApplicationDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentType,
			&i.Validation,
			&i.UploadedAt,
			&i.ExpiresAt,
			&i.Detail,
			&i.OcrRead,
			&i.OcrExpected,
			&i.SizeBytes,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminApplicationsAwaitingTypes = `-- name: AdminApplicationsAwaitingTypes :many
SELECT DISTINCT ON (d.application_id)
  d.application_id, d.document_type
FROM provider_application_documents d
WHERE d.application_id = ANY($1::uuid[])
  AND d.validation = 'missing'
ORDER BY d.application_id, d.created_at, d.document_type
`

type AdminApplicationsAwaitingTypesRow struct {
	ApplicationID uuid.UUID
	DocumentType  string
}

// The first still-missing document per application, for "awaiting police verification"
// rows. Batched over the page's ids; an application missing nothing has no row.
func (q *Queries) AdminApplicationsAwaitingTypes(ctx context.Context, applicationIds []uuid.UUID) ([]AdminApplicationsAwaitingTypesRow, error) {
	rows, err := q.db.Query(ctx, adminApplicationsAwaitingTypes, applicationIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminApplicationsAwaitingTypesRow{}
	for rows.Next() {
		var i AdminApplicationsAwaitingTypesRow
		if err := rows.Scan(&i.ApplicationID, &i.DocumentType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminApplicationsSummary = `-- name: AdminApplicationsSummary :one

SELECT
  count(*) FILTER (WHERE status = 'pending')::int AS pending,
  count(*) FILTER (WHERE status = 'awaiting_docs')::int AS awaiting_docs,
  count(*) FILTER (WHERE status IN ('approved', 'rejected'))::int AS decided,
  (min(applied_at) FILTER (WHERE status IN ('pending', 'awaiting_docs')))::timestamptz AS oldest_undecided_at
FROM provider_applications
`

type AdminApplicationsSummaryRow struct {
	Pending           int32
	AwaitingDocs      int32
	Decided           int32
	OldestUndecidedAt pgtype.Timestamptz
}

// ---------------------------------------------------------------------------
// Applications
// Queue chip counts plus the age of the oldest undecided application (the 48h SLA clock).
func (q *Queries) AdminApplicationsSummary(ctx context.Context) (AdminApplicationsSummaryRow, error) {
	row := q.db.QueryRow(ctx, adminApplicationsSummary)
	var i AdminApplicationsSummaryRow
	err := row.Scan(
		&i.Pending,
		&i.AwaitingDocs,
		&i.Decided,
		&i.OldestUndecidedAt,
	)
	return i, err
}

const adminCountPriorApplications = `-- name: AdminCountPriorApplications :one
SELECT count(*)::int AS prior
FROM provider_applications
WHERE phone = $1 AND id <> $2
`

type AdminCountPriorApplicationsParams struct {
	Phone         string
	ApplicationID uuid.UUID
}

// Earlier applications from the same phone — surfaced on the review screen.
func (q *Queries) AdminCountPriorApplications(ctx context.Context, arg AdminCountPriorApplicationsParams) (int32, error) {
	row := q.db.QueryRow(ctx, adminCountPriorApplications, arg.Phone, arg.ApplicationID)
	var prior int32
	err := row.Scan(&prior)
	return prior, err
}

const adminCountProviderRoster = `-- name: AdminCountProviderRoster :many
WITH derived AS (
  SELECT
    u.name,
    u.phone,
    t.city AS zone,
    CASE
      WHEN st.standing = 'BLOCKED' THEN 'offboarded'
      WHEN st.standing = 'SUSPENDED' AND st.suspended_until > now() THEN 'suspended'
      WHEN EXISTS (SELECT 1 FROM bookings b
                    WHERE b.technician_id = t.user_id
                      AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION'))
        THEN 'on_job'
      WHEN t.is_online AND NOT t.on_leave
           AND GREATEST(t.updated_at, COALESCE(t.last_location_at, t.updated_at))
               > now() - make_interval(secs => $2::int)
        THEN 'free'
      ELSE 'offline'
    END::text AS status
  FROM technicians t
  JOIN users u ON u.id = t.user_id
  LEFT JOIN provider_admin_states st ON st.technician_id = t.user_id
  WHERE u.deleted_at IS NULL
)
SELECT d.status, count(*)::int AS total
FROM derived d
WHERE ($1::text IS NULL
       OR d.name  ILIKE $1
       OR d.phone LIKE  $1
       OR d.zone  ILIKE $1)
GROUP BY d.status
`

type AdminCountProviderRosterParams struct {
	SearchPattern     *string
	StaleAfterSeconds int32
}

type AdminCountProviderRosterRow struct {
	Status string
	Total  int32
}

// Per-derived-status totals under the SAME search filter as the roster page (but not the
// segment filter), so the segment chips stay honest while a search is applied.
func (q *Queries) AdminCountProviderRoster(ctx context.Context, arg AdminCountProviderRosterParams) ([]AdminCountProviderRosterRow, error) {
	rows, err := q.db.Query(ctx, adminCountProviderRoster, arg.SearchPattern, arg.StaleAfterSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminCountProviderRosterRow{}
	for rows.Next() {
		var i AdminCountProviderRosterRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetApplication = `-- name: AdminGetApplication :one
SELECT
  a.id, a.applicant_name, a.phone, a.email, a.address, a.zone, a.status,
  a.documents_required, a.background_cleared_at, a.applied_at,
  a.decided_at, a.decision_reason_code, a.decision_note, a.version,
  a.documents_requested_at, a.documents_request_note,
  decider.name AS decided_by_name
FROM provider_applications a
LEFT JOIN users decider ON decider.id = a.decided_by
WHERE a.id = $1
`

type AdminGetApplicationRow struct {
	ID                   uuid.UUID
	ApplicantName        string
	Phone                string
	Email                string
	Address              string
	Zone                 string
	Status               string
	DocumentsRequired    int32
	BackgroundClearedAt  pgtype.Timestamptz
	AppliedAt            pgtype.Timestamptz
	DecidedAt            pgtype.Timestamptz
	DecisionReasonCode   *string
	DecisionNote         string
	Version              int64
	DocumentsRequestedAt pgtype.Timestamptz
	DocumentsRequestNote string
	DecidedByName        *string
}

func (q *Queries) AdminGetApplication(ctx context.Context, applicationID uuid.UUID) (AdminGetApplicationRow, error) {
	row := q.db.QueryRow(ctx, adminGetApplication, applicationID)
	var i AdminGetApplicationRow
	err := row.Scan(
		&i.ID,
		&i.ApplicantName,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.Zone,
		&i.Status,
		&i.DocumentsRequired,
		&i.BackgroundClearedAt,
		&i.AppliedAt,
		&i.DecidedAt,
		&i.DecisionReasonCode,
		&i.DecisionNote,
		&i.Version,
		&i.DocumentsRequestedAt,
		&i.DocumentsRequestNote,
		&i.DecidedByName,
	)
	return i, err
}

const adminGetProvider = `-- name: AdminGetProvider :one
SELECT
  t.user_id,
  u.name,
  u.phone,
  u.created_at AS joined_at,
  t.city AS zone,
  t.rating,
  GREATEST(t.updated_at, COALESCE(t.last_location_at, t.updated_at))::timestamptz AS last_seen_at,
  st.standing,
  st.reason_code,
  st.note AS standing_note,
  st.suspended_until,
  st.decided_at,
  COALESCE(st.version, 0)::bigint AS standing_version,
  decider.name AS decided_by_name,
  CASE
    WHEN st.standing = 'BLOCKED' THEN 'offboarded'
    WHEN st.standing = 'SUSPENDED' AND st.suspended_until > now() THEN 'suspended'
    WHEN EXISTS (SELECT 1 FROM bookings b
                  WHERE b.technician_id = t.user_id
                    AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION'))
      THEN 'on_job'
    WHEN t.is_online AND NOT t.on_leave
         AND GREATEST(t.updated_at, COALESCE(t.last_location_at, t.updated_at))
             > now() - make_interval(secs => $1::int)
      THEN 'free'
    ELSE 'offline'
  END::text AS status
FROM technicians t
JOIN users u ON u.id = t.user_id
LEFT JOIN provider_admin_states st ON st.technician_id = t.user_id
LEFT JOIN users decider ON decider.id = st.decided_by
WHERE t.user_id = $2 AND u.deleted_at IS NULL
`

type AdminGetProviderParams struct {
	StaleAfterSeconds int32
	TechnicianID      uuid.UUID
}

type AdminGetProviderRow struct {
	UserID          uuid.UUID
	Name            string
	Phone           string
	JoinedAt        pgtype.Timestamptz
	Zone            string
	Rating          pgtype.Numeric
	LastSeenAt      pgtype.Timestamptz
	Standing        *string
	ReasonCode      *string
	StandingNote    *string
	SuspendedUntil  pgtype.Timestamptz
	DecidedAt       pgtype.Timestamptz
	StandingVersion int64
	DecidedByName   *string
	Status          string
}

// The provider profile's core row: identity, standing (absent row = ACTIVE at version 0)
// and the same derived status the roster computes.
func (q *Queries) AdminGetProvider(ctx context.Context, arg AdminGetProviderParams) (AdminGetProviderRow, error) {
	row := q.db.QueryRow(ctx, adminGetProvider, arg.StaleAfterSeconds, arg.TechnicianID)
	var i AdminGetProviderRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Phone,
		&i.JoinedAt,
		&i.Zone,
		&i.Rating,
		&i.LastSeenAt,
		&i.Standing,
		&i.ReasonCode,
		&i.StandingNote,
		&i.SuspendedUntil,
		&i.DecidedAt,
		&i.StandingVersion,
		&i.DecidedByName,
		&i.Status,
	)
	return i, err
}

const adminListApplications = `-- name: AdminListApplications :many
SELECT
  a.id, a.applicant_name, a.zone, a.applied_at, a.status, a.decided_at, a.documents_required,
  COALESCE(docs.present, 0)::int AS documents_present,
  COALESCE(cats.names, '{}')::text[] AS categories
FROM provider_applications a
LEFT JOIN LATERAL (
  SELECT count(*) FILTER (WHERE d.validation <> 'missing') AS present
  FROM provider_application_documents d
  WHERE d.application_id = a.id
) docs ON true
LEFT JOIN LATERAL (
  SELECT array_agg(c.name ORDER BY c.name) AS names
  FROM provider_application_categories c
  WHERE c.application_id = a.id
) cats ON true
WHERE a.status = ANY($1::text[])
  AND ($2::timestamptz IS NULL
       OR a.applied_at > $2::timestamptz
       OR (a.applied_at = $2::timestamptz
           AND a.id > $3::uuid))
ORDER BY a.applied_at, a.id
LIMIT $4::int
`

type AdminListApplicationsParams struct {
	Statuses        []string
	CursorAppliedAt pgtype.Timestamptz
	CursorID        *uuid.UUID
	RowLimit        int32
}

type AdminListApplicationsRow struct {
	ID                uuid.UUID
	ApplicantName     string
	Zone              string
	AppliedAt         pgtype.Timestamptz
	Status            string
	DecidedAt         pgtype.Timestamptz
	DocumentsRequired int32
	DocumentsPresent  int32
	Categories        []string
}

// The application queue, oldest first (the applicant who has waited longest is reviewed
// first), keyset-paginated on (applied_at, id).
func (q *Queries) AdminListApplications(ctx context.Context, arg AdminListApplicationsParams) ([]AdminListApplicationsRow, error) {
	rows, err := q.db.Query(ctx, adminListApplications,
		arg.Statuses,
		arg.CursorAppliedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListApplicationsRow{}
	for rows.Next() {
		var i AdminListApplicationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicantName,
			&i.Zone,
			&i.AppliedAt,
			&i.Status,
			&i.DecidedAt,
			&i.DocumentsRequired,
			&i.DocumentsPresent,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListProviderRoster = `-- name: AdminListProviderRoster :many

WITH derived AS (
  SELECT
    t.user_id,
    u.name,
    u.phone,
    t.city AS zone,
    t.rating,
    GREATEST(t.updated_at, COALESCE(t.last_location_at, t.updated_at)) AS last_seen_at,
    st.suspended_until,
    CASE
      WHEN st.standing = 'BLOCKED' THEN 'offboarded'
      WHEN st.standing = 'SUSPENDED' AND st.suspended_until > now() THEN 'suspended'
      WHEN EXISTS (SELECT 1 FROM bookings b
                    WHERE b.technician_id = t.user_id
                      AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION'))
        THEN 'on_job'
      WHEN t.is_online AND NOT t.on_leave
           AND GREATEST(t.updated_at, COALESCE(t.last_location_at, t.updated_at))
               > now() - make_interval(secs => $7::int)
        THEN 'free'
      ELSE 'offline'
    END::text AS status
  FROM technicians t
  JOIN users u ON u.id = t.user_id
  LEFT JOIN provider_admin_states st ON st.technician_id = t.user_id
  WHERE u.deleted_at IS NULL
)
SELECT
  d.user_id, d.name, d.zone, d.status, d.rating, d.suspended_until,
  d.last_seen_at::timestamptz AS last_seen_at,
  COALESCE(skill_list.names, '{}')::text[] AS skills,
  COALESCE(window_stats.completed, 0)::int AS completed_90,
  COALESCE(window_stats.terminal, 0)::int  AS terminal_90,
  COALESCE(today.completed, 0)::int        AS completed_today,
  COALESCE(today.earnings, 0)::bigint      AS earnings_today,
  COALESCE(active.jobs, 0)::int            AS active_jobs
FROM derived d
LEFT JOIN LATERAL (
  SELECT array_agg(sk.name ORDER BY sk.name) AS names
  FROM technician_skills ts
  JOIN skills sk ON sk.id = ts.skill_id
  WHERE ts.technician_id = d.user_id
) skill_list ON true
LEFT JOIN LATERAL (
  SELECT count(*) FILTER (WHERE b.state = 'COMPLETED') AS completed,
         count(*) FILTER (WHERE b.state IN ('COMPLETED', 'CANCELLED', 'FAILED')) AS terminal
  FROM bookings b
  WHERE b.technician_id = d.user_id
    AND b.created_at > now() - interval '90 days'
) window_stats ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS completed, COALESCE(sum(b.quoted_total_paise), 0) AS earnings
  FROM bookings b
  JOIN booking_events be ON be.booking_id = b.id AND be.to_state = 'COMPLETED'
  WHERE b.technician_id = d.user_id
    AND be.created_at >= $1::timestamptz
) today ON true
LEFT JOIN LATERAL (
  SELECT count(*) AS jobs
  FROM bookings b
  WHERE b.technician_id = d.user_id
    AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION')
) active ON true
WHERE (cardinality($2::text[]) = 0 OR d.status = ANY($2::text[]))
  AND ($3::text IS NULL
       OR d.name  ILIKE $3
       OR d.phone LIKE  $3
       OR d.zone  ILIKE $3)
  AND ($4::text IS NULL
       OR d.name > $4::text
       OR (d.name = $4::text AND d.user_id > $5::uuid))
ORDER BY d.name, d.user_id
LIMIT $6::int
`

type AdminListProviderRosterParams struct {
	TodayStart        pgtype.Timestamptz
	Statuses          []string
	SearchPattern     *string
	CursorName        *string
	CursorID          *uuid.UUID
	RowLimit          int32
	StaleAfterSeconds int32
}

type AdminListProviderRosterRow struct {
	UserID         uuid.UUID
	Name           string
	Zone           string
	Status         string
	Rating         pgtype.Numeric
	SuspendedUntil pgtype.Timestamptz
	LastSeenAt     pgtype.Timestamptz
	Skills         []string
	Completed90    int32
	Terminal90     int32
	CompletedToday int32
	EarningsToday  int64
	ActiveJobs     int32
}

// The admin console's provider surface (internal/providerops): the roster read model, the
// provider profile aggregates, the standing writes (suspend / block / restore), and the
// provider-application pipeline.
//
// The roster STATUS is derived, never stored: BLOCKED standing -> offboarded; a live
// SUSPENDED standing -> suspended; an active booking -> on_job; online + not on leave +
// seen recently -> free; anything else -> offline. "Seen recently" reads
// GREATEST(updated_at, last_location_at) so a technician who toggled online but never
// shared a location is still fresh for the staleness window after the toggle.
func (q *Queries) AdminListProviderRoster(ctx context.Context, arg AdminListProviderRosterParams) ([]AdminListProviderRosterRow, error) {
	rows, err := q.db.Query(ctx, adminListProviderRoster,
		arg.TodayStart,
		arg.Statuses,
		arg.SearchPattern,
		arg.CursorName,
		arg.CursorID,
		arg.RowLimit,
		arg.StaleAfterSeconds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListProviderRosterRow{}
	for rows.Next() {
		var i AdminListProviderRosterRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Zone,
			&i.Status,
			&i.Rating,
			&i.SuspendedUntil,
			&i.LastSeenAt,
			&i.Skills,
			&i.Completed90,
			&i.Terminal90,
			&i.CompletedToday,
			&i.EarningsToday,
			&i.ActiveJobs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminProviderActiveJobs = `-- name: AdminProviderActiveJobs :many
SELECT
  b.id, b.state, b.quoted_total_paise,
  u.name AS customer_name,
  s.name AS service_name,
  a.city,
  (SELECT max(be.created_at) FROM booking_events be
    WHERE be.booking_id = b.id AND be.action = 'VERIFY_START')::timestamptz AS started_at
FROM bookings b
JOIN users u          ON u.id = b.customer_id
JOIN booking_items bi ON bi.booking_id = b.id
JOIN services s       ON s.id = bi.service_id
JOIN addresses a      ON a.id = b.address_id
WHERE b.technician_id = $1
  AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION')
ORDER BY b.created_at, b.id
`

type AdminProviderActiveJobsRow struct {
	ID               uuid.UUID
	State            string
	QuotedTotalPaise money.Money
	CustomerName     string
	ServiceName      string
	City             string
	StartedAt        pgtype.Timestamptz
}

// The provider's live jobs — step 3 of the suspend flow. started_at is the VERIFY_START
// transition when work has begun.
func (q *Queries) AdminProviderActiveJobs(ctx context.Context, technicianID *uuid.UUID) ([]AdminProviderActiveJobsRow, error) {
	rows, err := q.db.Query(ctx, adminProviderActiveJobs, technicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminProviderActiveJobsRow{}
	for rows.Next() {
		var i AdminProviderActiveJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.QuotedTotalPaise,
			&i.CustomerName,
			&i.ServiceName,
			&i.City,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminProviderCurrentJobs = `-- name: AdminProviderCurrentJobs :many
SELECT DISTINCT ON (b.technician_id)
  b.technician_id, b.id, b.state
FROM bookings b
WHERE b.technician_id = ANY($1::uuid[])
  AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION')
ORDER BY b.technician_id, b.updated_at DESC
`

type AdminProviderCurrentJobsRow struct {
	TechnicianID *uuid.UUID
	ID           uuid.UUID
	State        string
}

// The most recently touched live booking per technician, for the roster page's stage cell.
// Batched over the page's ids; a technician with no live job simply has no row.
func (q *Queries) AdminProviderCurrentJobs(ctx context.Context, technicianIds []uuid.UUID) ([]AdminProviderCurrentJobsRow, error) {
	rows, err := q.db.Query(ctx, adminProviderCurrentJobs, technicianIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminProviderCurrentJobsRow{}
	for rows.Next() {
		var i AdminProviderCurrentJobsRow
		if err := rows.Scan(&i.TechnicianID, &i.ID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminProviderFeedback = `-- name: AdminProviderFeedback :many
SELECT r.id, r.rating, r.comment, r.created_at, u.name AS author
FROM reviews r
JOIN users u ON u.id = r.customer_id
WHERE r.technician_id = $1 AND r.comment <> ''
ORDER BY r.created_at DESC, r.id DESC
LIMIT $2::int
`

type AdminProviderFeedbackParams struct {
	TechnicianID uuid.UUID
	RowLimit     int32
}

type AdminProviderFeedbackRow struct {
	ID        uuid.UUID
	Rating    int32
	Comment   string
	CreatedAt pgtype.Timestamptz
	Author    string
}

// Written customer feedback, newest first.
func (q *Queries) AdminProviderFeedback(ctx context.Context, arg AdminProviderFeedbackParams) ([]AdminProviderFeedbackRow, error) {
	rows, err := q.db.Query(ctx, adminProviderFeedback, arg.TechnicianID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminProviderFeedbackRow{}
	for rows.Next() {
		var i AdminProviderFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminProviderJobStats = `-- name: AdminProviderJobStats :one
SELECT
  (SELECT count(*) FROM bookings b
    WHERE b.technician_id = $1 AND b.state = 'COMPLETED')::int AS jobs_total,
  (SELECT count(*) FROM bookings b
    JOIN booking_events be ON be.booking_id = b.id AND be.to_state = 'COMPLETED'
    WHERE b.technician_id = $1
      AND be.created_at >= $2::timestamptz)::int AS completed_today,
  (SELECT count(*) FROM bookings b
    WHERE b.technician_id = $1
      AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION'))::int AS active_now,
  (SELECT COALESCE(sum(b.quoted_total_paise), 0) FROM bookings b
    JOIN booking_events be ON be.booking_id = b.id AND be.to_state = 'COMPLETED'
    WHERE b.technician_id = $1
      AND be.created_at >= $2::timestamptz)::bigint AS earnings_today,
  (SELECT COALESCE(sum(b.quoted_total_paise), 0) FROM bookings b
    JOIN booking_events be ON be.booking_id = b.id AND be.to_state = 'COMPLETED'
    WHERE b.technician_id = $1
      AND be.created_at >= $3::timestamptz)::bigint AS cycle_revenue
`

type AdminProviderJobStatsParams struct {
	TechnicianID *uuid.UUID
	TodayStart   pgtype.Timestamptz
	CycleStart   pgtype.Timestamptz
}

type AdminProviderJobStatsRow struct {
	JobsTotal      int32
	CompletedToday int32
	ActiveNow      int32
	EarningsToday  int64
	CycleRevenue   int64
}

// The profile's headline aggregates, all from real bookings. "Completed today/this cycle"
// is dated by the booking_events row that moved the booking to COMPLETED.
func (q *Queries) AdminProviderJobStats(ctx context.Context, arg AdminProviderJobStatsParams) (AdminProviderJobStatsRow, error) {
	row := q.db.QueryRow(ctx, adminProviderJobStats, arg.TechnicianID, arg.TodayStart, arg.CycleStart)
	var i AdminProviderJobStatsRow
	err := row.Scan(
		&i.JobsTotal,
		&i.CompletedToday,
		&i.ActiveNow,
		&i.EarningsToday,
		&i.CycleRevenue,
	)
	return i, err
}

const adminProviderPerformanceBuckets = `-- name: AdminProviderPerformanceBuckets :many
SELECT
  width_bucket(
    EXTRACT(EPOCH FROM b.created_at),
    EXTRACT(EPOCH FROM $1::timestamptz),
    EXTRACT(EPOCH FROM $2::timestamptz), 8
  )::int AS bucket,
  count(*)::int AS assigned,
  count(*) FILTER (WHERE b.state = 'COMPLETED')::int AS completed,
  count(*) FILTER (WHERE b.state IN ('CANCELLED', 'FAILED'))::int AS cancelled,
  count(*) FILTER (WHERE b.state IN ('COMPLETED', 'CANCELLED', 'FAILED'))::int AS terminal,
  count(*) FILTER (WHERE EXISTS (
    SELECT 1 FROM booking_events be
    WHERE be.booking_id = b.id AND be.to_state = 'ESCALATED'))::int AS escalated
FROM bookings b
WHERE b.technician_id = $3
  AND b.created_at >= $1::timestamptz AND b.created_at < $2::timestamptz
GROUP BY 1
`

type AdminProviderPerformanceBucketsParams struct {
	FromTime     pgtype.Timestamptz
	ToTime       pgtype.Timestamptz
	TechnicianID *uuid.UUID
}

type AdminProviderPerformanceBucketsRow struct {
	Bucket    int32
	Assigned  int32
	Completed int32
	Cancelled int32
	Terminal  int32
	Escalated int32
}

// The 90-day performance trend in 8 equal buckets (by booking creation): jobs assigned,
// completions, cancellations/failures, terminal outcomes and escalations.
func (q *Queries) AdminProviderPerformanceBuckets(ctx context.Context, arg AdminProviderPerformanceBucketsParams) ([]AdminProviderPerformanceBucketsRow, error) {
	rows, err := q.db.Query(ctx, adminProviderPerformanceBuckets, arg.FromTime, arg.ToTime, arg.TechnicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminProviderPerformanceBucketsRow{}
	for rows.Next() {
		var i AdminProviderPerformanceBucketsRow
		if err := rows.Scan(
			&i.Bucket,
			&i.Assigned,
			&i.Completed,
			&i.Cancelled,
			&i.Terminal,
			&i.Escalated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminProviderRatingBuckets = `-- name: AdminProviderRatingBuckets :many
SELECT
  width_bucket(
    EXTRACT(EPOCH FROM r.created_at),
    EXTRACT(EPOCH FROM $1::timestamptz),
    EXTRACT(EPOCH FROM $2::timestamptz), 8
  )::int AS bucket,
  avg(r.rating)::float8 AS avg_rating
FROM reviews r
WHERE r.technician_id = $3
  AND r.created_at >= $1::timestamptz AND r.created_at < $2::timestamptz
GROUP BY 1
`

type AdminProviderRatingBucketsParams struct {
	FromTime     pgtype.Timestamptz
	ToTime       pgtype.Timestamptz
	TechnicianID uuid.UUID
}

type AdminProviderRatingBucketsRow struct {
	Bucket    int32
	AvgRating float64
}

// Review ratings over the same 8-bucket window, for the rating trend.
func (q *Queries) AdminProviderRatingBuckets(ctx context.Context, arg AdminProviderRatingBucketsParams) ([]AdminProviderRatingBucketsRow, error) {
	rows, err := q.db.Query(ctx, adminProviderRatingBuckets, arg.FromTime, arg.ToTime, arg.TechnicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminProviderRatingBucketsRow{}
	for rows.Next() {
		var i AdminProviderRatingBucketsRow
		if err := rows.Scan(&i.Bucket, &i.AvgRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminProviderRecentJobs = `-- name: AdminProviderRecentJobs :many
SELECT
  b.id, b.state, b.created_at, b.quoted_total_paise,
  s.name AS service_name,
  r.rating AS review_rating,
  COALESCE(
    (SELECT max(be.created_at) FROM booking_events be
      WHERE be.booking_id = b.id AND be.to_state = b.state),
    b.created_at
  )::timestamptz AS state_at
FROM bookings b
JOIN booking_items bi ON bi.booking_id = b.id
JOIN services s       ON s.id = bi.service_id
LEFT JOIN reviews r   ON r.booking_id = b.id
WHERE b.technician_id = $1
  AND b.state IN ('COMPLETED', 'CANCELLED', 'FAILED')
ORDER BY b.created_at DESC, b.id DESC
LIMIT $2::int
`

type AdminProviderRecentJobsParams struct {
	TechnicianID *uuid.UUID
	RowLimit     int32
}

type AdminProviderRecentJobsRow struct {
	ID               uuid.UUID
	State            string
	CreatedAt        pgtype.Timestamptz
	QuotedTotalPaise money.Money
	ServiceName      string
	ReviewRating     *int32
	StateAt          pgtype.Timestamptz
}

// The profile's recent-jobs table: finished bookings, newest first, with the review each
// one earned. state_at is when the booking reached its terminal state.
func (q *Queries) AdminProviderRecentJobs(ctx context.Context, arg AdminProviderRecentJobsParams) ([]AdminProviderRecentJobsRow, error) {
	rows, err := q.db.Query(ctx, adminProviderRecentJobs, arg.TechnicianID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminProviderRecentJobsRow{}
	for rows.Next() {
		var i AdminProviderRecentJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.CreatedAt,
			&i.QuotedTotalPaise,
			&i.ServiceName,
			&i.ReviewRating,
			&i.StateAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminProviderSkills = `-- name: AdminProviderSkills :many
SELECT sk.name
FROM technician_skills ts
JOIN skills sk ON sk.id = ts.skill_id
WHERE ts.technician_id = $1
ORDER BY sk.name
`

func (q *Queries) AdminProviderSkills(ctx context.Context, technicianID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, adminProviderSkills, technicianID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminZoneOnlineCounts = `-- name: AdminZoneOnlineCounts :many
WITH derived AS (
  SELECT
    t.city AS zone,
    CASE
      WHEN st.standing = 'BLOCKED' THEN 'offboarded'
      WHEN st.standing = 'SUSPENDED' AND st.suspended_until > now() THEN 'suspended'
      WHEN EXISTS (SELECT 1 FROM bookings b
                    WHERE b.technician_id = t.user_id
                      AND b.state IN ('ASSIGNED', 'EN_ROUTE', 'ARRIVED', 'IN_PROGRESS', 'AWAITING_COMPLETION'))
        THEN 'on_job'
      WHEN t.is_online AND NOT t.on_leave
           AND GREATEST(t.updated_at, COALESCE(t.last_location_at, t.updated_at))
               > now() - make_interval(secs => $1::int)
        THEN 'free'
      ELSE 'offline'
    END::text AS status
  FROM technicians t
  JOIN users u ON u.id = t.user_id
  LEFT JOIN provider_admin_states st ON st.technician_id = t.user_id
  WHERE u.deleted_at IS NULL
)
SELECT d.zone, count(*) FILTER (WHERE d.status IN ('free', 'on_job'))::int AS online_count
FROM derived d
GROUP BY d.zone
ORDER BY d.zone
`

type AdminZoneOnlineCountsRow struct {
	Zone        string
	OnlineCount int32
}

// Online (free or on-job) providers per zone — the roster's supply-health strip.
func (q *Queries) AdminZoneOnlineCounts(ctx context.Context, staleAfterSeconds int32) ([]AdminZoneOnlineCountsRow, error) {
	rows, err := q.db.Query(ctx, adminZoneOnlineCounts, staleAfterSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminZoneOnlineCountsRow{}
	for rows.Next() {
		var i AdminZoneOnlineCountsRow
		if err := rows.Scan(&i.Zone, &i.OnlineCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bumpProviderStandingVersion = `-- name: BumpProviderStandingVersion :one
INSERT INTO provider_admin_states AS pas (technician_id)
VALUES ($1)
ON CONFLICT (technician_id) DO UPDATE
   SET updated_at = now(),
       version    = pas.version + 1
 WHERE pas.version = $2
RETURNING version
`

type BumpProviderStandingVersionParams struct {
	TechnicianID    uuid.UUID
	ExpectedVersion int64
}

// Force-offline changes availability (identity's aggregate), not standing — but it still
// consumes the provider's concurrency token, so two admins acting on a stale profile still
// collide. Inserts the implicit ACTIVE row on first touch.
func (q *Queries) BumpProviderStandingVersion(ctx context.Context, arg BumpProviderStandingVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpProviderStandingVersion, arg.TechnicianID, arg.ExpectedVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const decideApplication = `-- name: DecideApplication :one
UPDATE provider_applications
   SET status                 = $1,
       decided_at             = now(),
       decided_by             = $2,
       decision_reason_code   = $3,
       decision_note          = $4,
       approved_technician_id = $5,
       updated_at             = now(),
       version                = version + 1
 WHERE id = $6
   AND version = $7
   AND status IN ('pending', 'awaiting_docs')
RETURNING version
`

type DecideApplicationParams struct {
	Status               string
	DecidedBy            *uuid.UUID
	DecisionReasonCode   *string
	DecisionNote         string
	ApprovedTechnicianID *uuid.UUID
	ApplicationID        uuid.UUID
	ExpectedVersion      int64
}

// THE COMPARE-AND-SWAP for a decision, doubly guarded: the version must match AND the
// application must still be undecided (a decision is terminal — approved/rejected rows can
// never be decided again, whatever version a caller replays).
func (q *Queries) DecideApplication(ctx context.Context, arg DecideApplicationParams) (int64, error) {
	row := q.db.QueryRow(ctx, decideApplication,
		arg.Status,
		arg.DecidedBy,
		arg.DecisionReasonCode,
		arg.DecisionNote,
		arg.ApprovedTechnicianID,
		arg.ApplicationID,
		arg.ExpectedVersion,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const ensureApplicationDocumentRequested = `-- name: EnsureApplicationDocumentRequested :exec
INSERT INTO provider_application_documents (application_id, document_type)
VALUES ($1, $2)
ON CONFLICT (application_id, document_type) DO NOTHING
`

type EnsureApplicationDocumentRequestedParams struct {
	ApplicationID uuid.UUID
	DocumentType  string
}

// A requested document appears on the checklist as 'missing' until the applicant files it.
// Idempotent: re-requesting a type that already has a row changes nothing.
func (q *Queries) EnsureApplicationDocumentRequested(ctx context.Context, arg EnsureApplicationDocumentRequestedParams) error {
	_, err := q.db.Exec(ctx, ensureApplicationDocumentRequested, arg.ApplicationID, arg.DocumentType)
	return err
}

const getProviderStandingVersion = `-- name: GetProviderStandingVersion :one
SELECT standing, version
FROM provider_admin_states
WHERE technician_id = $1
`

type GetProviderStandingVersionRow struct {
	Standing string
	Version  int64
}

// The optimistic-concurrency read for standing writes. No row means ACTIVE at version 0
// (the caller treats ErrNoRows that way).
func (q *Queries) GetProviderStandingVersion(ctx context.Context, technicianID uuid.UUID) (GetProviderStandingVersionRow, error) {
	row := q.db.QueryRow(ctx, getProviderStandingVersion, technicianID)
	var i GetProviderStandingVersionRow
	err := row.Scan(&i.Standing, &i.Version)
	return i, err
}

const markApplicationAwaitingDocuments = `-- name: MarkApplicationAwaitingDocuments :one
UPDATE provider_applications
   SET status                 = 'awaiting_docs',
       documents_requested_at = now(),
       documents_request_note = $1,
       updated_at             = now(),
       version                = version + 1
 WHERE id = $2
   AND version = $3
   AND status IN ('pending', 'awaiting_docs')
RETURNING version, documents_requested_at
`

type MarkApplicationAwaitingDocumentsParams struct {
	Note            string
	ApplicationID   uuid.UUID
	ExpectedVersion int64
}

type MarkApplicationAwaitingDocumentsRow struct {
	Version              int64
	DocumentsRequestedAt pgtype.Timestamptz
}

// Request-documents: same CAS + still-undecided guard as a decision.
func (q *Queries) MarkApplicationAwaitingDocuments(ctx context.Context, arg MarkApplicationAwaitingDocumentsParams) (MarkApplicationAwaitingDocumentsRow, error) {
	row := q.db.QueryRow(ctx, markApplicationAwaitingDocuments, arg.Note, arg.ApplicationID, arg.ExpectedVersion)
	var i MarkApplicationAwaitingDocumentsRow
	err := row.Scan(&i.Version, &i.DocumentsRequestedAt)
	return i, err
}

const upsertProviderStanding = `-- name: UpsertProviderStanding :one
INSERT INTO provider_admin_states AS pas
    (technician_id, standing, reason_code, note, suspended_until, decided_by, decided_at)
VALUES ($1, $2, $3, $4,
        $5, $6, now())
ON CONFLICT (technician_id) DO UPDATE
   SET standing        = EXCLUDED.standing,
       reason_code     = EXCLUDED.reason_code,
       note            = EXCLUDED.note,
       suspended_until = EXCLUDED.suspended_until,
       decided_by      = EXCLUDED.decided_by,
       decided_at      = now(),
       updated_at      = now(),
       version         = pas.version + 1
 WHERE pas.version = $7
RETURNING version
`

type UpsertProviderStandingParams struct {
	TechnicianID    uuid.UUID
	Standing        string
	ReasonCode      *string
	Note            string
	SuspendedUntil  pgtype.Timestamptz
	DecidedBy       *uuid.UUID
	ExpectedVersion int64
}

// THE COMPARE-AND-SWAP for a standing change. A first-ever write inserts at version 1 (the
// service has already verified the expected version was 0, inside the same transaction); a
// later write only lands when the version still matches — zero rows means another admin got
// there first, which the service turns into the 409 the console renders.
func (q *Queries) UpsertProviderStanding(ctx context.Context, arg UpsertProviderStandingParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertProviderStanding,
		arg.TechnicianID,
		arg.Standing,
		arg.ReasonCode,
		arg.Note,
		arg.SuspendedUntil,
		arg.DecidedBy,
		arg.ExpectedVersion,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}
