// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getBookingCustomerPhone = `-- name: GetBookingCustomerPhone :one
SELECT u.phone
  FROM bookings b
  JOIN users u ON u.id = b.customer_id
 WHERE b.id = $1
`

func (q *Queries) GetBookingCustomerPhone(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getBookingCustomerPhone, id)
	var phone string
	err := row.Scan(&phone)
	return phone, err
}

const getLiveJobOtpChallenge = `-- name: GetLiveJobOtpChallenge :one
SELECT id, code_hash, attempts, max_attempts
  FROM otp_challenges
 WHERE booking_id = $1
   AND purpose = $2
   AND consumed_at IS NULL
   AND expires_at > now()
 ORDER BY created_at DESC
 LIMIT 1
`

type GetLiveJobOtpChallengeParams struct {
	BookingID *uuid.UUID
	Purpose   string
}

type GetLiveJobOtpChallengeRow struct {
	ID          uuid.UUID
	CodeHash    string
	Attempts    int32
	MaxAttempts int32
}

// The live challenge for this booking and purpose: not consumed, not expired.
func (q *Queries) GetLiveJobOtpChallenge(ctx context.Context, arg GetLiveJobOtpChallengeParams) (GetLiveJobOtpChallengeRow, error) {
	row := q.db.QueryRow(ctx, getLiveJobOtpChallenge, arg.BookingID, arg.Purpose)
	var i GetLiveJobOtpChallengeRow
	err := row.Scan(
		&i.ID,
		&i.CodeHash,
		&i.Attempts,
		&i.MaxAttempts,
	)
	return i, err
}

const insertJobOtpChallenge = `-- name: InsertJobOtpChallenge :one
INSERT INTO otp_challenges (purpose, booking_id, phone, code_hash, expires_at, max_attempts)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertJobOtpChallengeParams struct {
	Purpose     string
	BookingID   *uuid.UUID
	Phone       string
	CodeHash    string
	ExpiresAt   pgtype.Timestamptz
	MaxAttempts int32
}

// A START or COMPLETION OTP, bound to a booking (the CHECK requires booking_id for these
// purposes). The code goes to the customer's phone; the technician reads it back from them.
func (q *Queries) InsertJobOtpChallenge(ctx context.Context, arg InsertJobOtpChallengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertJobOtpChallenge,
		arg.Purpose,
		arg.BookingID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.MaxAttempts,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
